In [1]:
import pandas as pd
import joblib

nifty_500 = pd.read_csv('ind_nifty500list.csv')
stocks = nifty_500['Symbol'].values.tolist()
print(stocks)
stocks = pd.DataFrame(stocks)
stocks

['360ONE', '3MINDIA', 'ABB', 'ACC', 'AIAENG', 'APLAPOLLO', 'AUBANK', 'AARTIDRUGS', 'AARTIIND', 'AAVAS', 'ABBOTINDIA', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ATGL', 'ADANITRANS', 'AWL', 'ABCAPITAL', 'ABFRL', 'AEGISCHEM', 'AETHER', 'AFFLE', 'AJANTPHARM', 'APLLTD', 'ALKEM', 'ALKYLAMINE', 'AMARAJABAT', 'AMBER', 'AMBUJACEM', 'ANGELONE', 'ANURAS', 'APARINDS', 'APOLLOHOSP', 'APOLLOTYRE', 'APTUS', 'ACI', 'ASAHIINDIA', 'ASHOKLEY', 'ASIANPAINT', 'ASTERDM', 'ASTRAL', 'ATUL', 'AUROPHARMA', 'AVANTIFEED', 'DMART', 'AXISBANK', 'BASF', 'BEML', 'BLS', 'BSE', 'BAJAJ-AUTO', 'BAJAJELEC', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BERGEPAINT', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL', 'BHARTIARTL', 'BIKAJI', 'BIOCON', 'BIRLACORPN', 'BSOFT', 'BLUEDART', 'BLUESTARCO', 'BBTC', 'BORORENEW', 'BOSCHLTD', 'BRIGADE', 'BCG', 'BRITANNIA', 'MAPMYINDIA', 'CCL', 'CESC', 'CGPOWER', 'CRISIL', 'CSBBANK', 'CAMPUS', 'CANFINHOME', 'CANBK', 'CGCL', 'CARBORUNIV', 'CASTROLIND', 'CEATLTD', 'CENTRALBK', 'CDSL', 'CENTURYPLY', 'CENTURYTEX', 'CERA', 'CHALET', 'CHAMBLFERT', 'CHEMPLASTS', 'CHOLAHLDNG', 'CHOLAFIN', 'CIPLA', 'CUB', 'CLEAN', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CAMS', 'CONCOR', 'COROMANDEL', 'CRAFTSMAN', 'CREDITACC', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DCMSHRIRAM', 'DLF', 'DABUR', 'DALBHARAT', 'DATAPATTNS', 'DEEPAKFERT', 'DEEPAKNTR', 'DELHIVERY', 'DELTACORP', 'DEVYANI', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'EIHOTEL', 'EPL', 'EASEMYTRIP', 'EDELWEISS', 'EICHERMOT', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN', 'EQUITASBNK', 'ESCORTS', 'EXIDEIND', 'FDC', 'NYKAA', 'FEDERALBNK', 'FACT', 'FINEORG', 'FINCABLES', 'FINPIPE', 'FSL', 'FIVESTAR', 'FORTIS', 'GRINFRA', 'GAIL', 'GMMPFAUDLR', 'GMRINFRA', 'GALAXYSURF', 'GARFIBRES', 'GICRE', 'GLAND', 'GLAXO', 'GLENMARK', 'MEDANTA', 'GOCOLORS', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GESHIP', 'GREENPANEL', 'GRINDWELL', 'GUJALKALI', 'GAEL', 'FLUOROCHEM', 'GUJGASLTD', 'GNFC', 'GPPL', 'GSFC', 'GSPL', 'HEG', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HFCL', 'HLEGLAS', 'HAPPSTMNDS', 'HAVELLS', 'HEROMOTOCO', 'HIKAL', 'HINDALCO', 'HGS', 'HAL', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'POWERINDIA', 'HOMEFIRST', 'HONAUT', 'HUDCO', 'HDFC', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ISEC', 'IDBI', 'IDFCFIRSTB', 'IDFC', 'IFBIND', 'IIFL', 'IRB', 'ITC', 'ITI', 'INDIACEM', 'IBULHSGFIN', 'IBREALEST', 'INDIAMART', 'INDIANB', 'IEX', 'INDHOTEL', 'IOC', 'IOB', 'IRCTC', 'IRFC', 'INDIGOPNTS', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'INFIBEAM', 'NAUKRI', 'INFY', 'INGERRAND', 'INTELLECT', 'INDIGO', 'IPCALAB', 'JBCHEPHARM', 'JKCEMENT', 'JBMA', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSWENERGY', 'JSWSTEEL', 'JAMNAAUTO', 'JSL', 'JINDALSTEL', 'JINDWORLD', 'JUBLFOOD', 'JUBLINGREA', 'JUBLPHARMA', 'JUSTDIAL', 'JYOTHYLAB', 'KPRMILL', 'KEI', 'KNRCON', 'KPITTECH', 'KRBL', 'KSB', 'KAJARIACER', 'KALPATPOWR', 'KALYANKJIL', 'KANSAINER', 'KARURVYSYA', 'KEC', 'KENNAMET', 'RUSTOMJEE', 'KFINTECH', 'KOTAKBANK', 'KIMS', 'L&TFH', 'LTTS', 'LICHSGFIN', 'LTIM', 'LAXMIMACH', 'LT', 'LATENTVIEW', 'LAURUSLABS', 'LXCHEM', 'LEMONTREE', 'LICI', 'LINDEINDIA', 'LUPIN', 'LUXIND', 'MMTC', 'MRF', 'MTARTECH', 'LODHA', 'MGL', 'M&MFIN', 'M&M', 'MAHINDCIE', 'MHRIL', 'MAHLIFE', 'MAHLOG', 'MANAPPURAM', 'MRPL', 'MARICO', 'MARUTI', 'MASTEK', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'MEDPLUS', 'MFL', 'METROBRAND', 'METROPOLIS', 'MSUMI', 'MOTILALOFS', 'MPHASIS', 'MCX', 'MUTHOOTFIN', 'NATCOPHARM', 'NBCC', 'NCC', 'NHPC', 'NLCINDIA', 'NMDC', 'NOCIL', 'NTPC', 'NH', 'NATIONALUM', 'NAVINFLUOR', 'NAZARA', 'NESTLEIND', 'NETWORK18', 'NAM-INDIA', 'NUVOCO', 'OBEROIRLTY', 'ONGC', 'OIL', 'OLECTRA', 'PAYTM', 'OFSS', 'ORIENTELEC', 'POLICYBZR', 'PCBL', 'PIIND', 'PNBHOUSING', 'PNCINFRA', 'PVR', 'PAGEIND', 'PATANJALI', 'PERSISTENT', 'PETRONET', 'PFIZER', 'PHOENIXLTD', 'PIDILITIND', 'PEL', 'PPLPHARMA', 'POLYMED', 'POLYCAB', 'POLYPLEX', 'POONAWALLA', 'PFC', 'POWERGRID', 'PRAJIND', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PGHH', 'PNB', 'QUESS', 'RBLBANK', 'RECLTD', 'RHIM', 'RITES', 'RADICO', 'RVNL', 'RAIN', 'RAINBOW', 'RAJESHEXPO', 'RALLIS', 'RCF', 'RATNAMANI', 'RTNINDIA', 'RAYMOND', 'REDINGTON', 'RELAXO', 'RELIANCE', 'RBA', 'ROSSARI', 'ROUTE', 'SBICARD', 'SBILIFE', 'SJVN', 'SKFINDIA', 'SRF', 'MOTHERSON', 'SANOFI', 'SAPPHIRE', 'SCHAEFFLER', 'SHARDACROP', 'SHOPERSTOP', 'SHREECEM', 'RENUKA', 'SHRIRAMFIN', 'SHYAMMETL', 'SIEMENS', 'SOBHA', 'SOLARINDS', 'SONACOMS', 'SONATSOFTW', 'STARHEALTH', 'SBIN', 'SAIL', 'SWSOLAR', 'STLTECH', 'SUMICHEM', 'SPARC', 'SUNPHARMA', 'SUNTV', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNTECK', 'SUPRAJIT', 'SUPREMEIND', 'SUVENPHAR', 'SUZLON', 'SWANENERGY', 'SYNGENE', 'TCIEXP', 'TCNSBRANDS', 'TTKPRESTIG', 'TV18BRDCST', 'TVSMOTOR', 'TMB', 'TANLA', 'TATACHEM', 'TATACOMM', 'TCS', 'TATACONSUM', 'TATAELXSI', 'TATAINVEST', 'TATAMTRDVR', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TTML', 'TEAMLEASE', 'TECHM', 'TEJASNET', 'NIACL', 'RAMCOCEM', 'THERMAX', 'TIMKEN', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TCI', 'TRENT', 'TRIDENT', 'TRIVENI', 'TRITURBINE', 'TIINDIA', 'UCOBANK', 'UFLEX', 'UNOMINDA', 'UPL', 'UTIAMC', 'ULTRACEMCO', 'UNIONBANK', 'UBL', 'MCDOWELL-N', 'VGUARD', 'VMART', 'VIPIND', 'VAIBHAVGBL', 'VTL', 'VARROC', 'VBL', 'MANYAVAR', 'VEDL', 'VIJAYA', 'VINATIORGA', 'IDEA', 'VOLTAS', 'WELCORP', 'WELSPUNIND', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'YESBANK', 'ZFCVINDIA', 'ZEEL', 'ZENSARTECH', 'ZOMATO', 'ZYDUSLIFE', 'ZYDUSWELL', 'ECLERX']

              0
0        360ONE
1       3MINDIA
2           ABB
3           ACC
4        AIAENG
..          ...
496  ZENSARTECH
497      ZOMATO
498   ZYDUSLIFE
499   ZYDUSWELL
500      ECLERX

[501 rows x 1 columns]

In [2]:
#pip install yfinance

In [3]:
#import joblib

In [4]:
import yfinance as yf
import datetime

# Define the list of NSE companies to fetch data for
nse_companies1 = stocks[0] +'.NS'
nse_companies=[]
# Set the start and end dates
end_date = datetime.date.today()
start_date = end_date - datetime.timedelta(days=290)

# Create an empty dictionary to store the data for each company
data = {}
data_check = {}

# Loop through the list of companies and fetch their data
set1 =1 
for company in nse_companies1:
    
    data_check[company] = yf.download(company, start=start_date, end=end_date)
    
    data_check[company] = pd.DataFrame(data_check[company])
    df_temp = data_check[company] 
    #df_temp = df_temp.iloc[0:175]
    
    if df_temp.shape[0]<175:
        print('skipping',company,'as it has only',df_temp.shape[0],'values')
        continue
        
    data[company] = df_temp
    nse_companies.append(company)
    #print(data[company])
    #print(data[company].head())
    
    print(company,len(data[company]), set1,'out of 500 stocks imported')
    set1 = set1 +1
    
# Print the data for each company
#for company in data:
    #print(company)
    #print(len(data[company]))

[*********************100%***********************]  1 of 1 completed
360ONE.NS 195 1 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
3MINDIA.NS 195 2 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ABB.NS 195 3 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ACC.NS 195 4 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AIAENG.NS 195 5 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APLAPOLLO.NS 195 6 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AUBANK.NS 195 7 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AARTIDRUGS.NS 195 8 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AARTIIND.NS 195 9 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AAVAS.NS 195 10 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ABBOTINDIA.NS 195 11 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ADANIENT.NS 195 12 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ADANIGREEN.NS 195 13 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ADANIPORTS.NS 195 14 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ADANIPOWER.NS 195 15 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ATGL.NS 195 16 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ADANITRANS.NS 195 17 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AWL.NS 195 18 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ABCAPITAL.NS 195 19 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ABFRL.NS 195 20 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AEGISCHEM.NS 195 21 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AETHER.NS 195 22 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AFFLE.NS 195 23 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AJANTPHARM.NS 195 24 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APLLTD.NS 195 25 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ALKEM.NS 195 26 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ALKYLAMINE.NS 195 27 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AMARAJABAT.NS 195 28 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AMBER.NS 195 29 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AMBUJACEM.NS 195 30 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ANGELONE.NS 195 31 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ANURAS.NS 195 32 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APARINDS.NS 195 33 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APOLLOHOSP.NS 195 34 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APOLLOTYRE.NS 195 35 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
APTUS.NS 195 36 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping ACI.NS as it has only 106 values
[*********************100%***********************]  1 of 1 completed
ASAHIINDIA.NS 195 37 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ASHOKLEY.NS 195 38 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ASIANPAINT.NS 195 39 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ASTERDM.NS 195 40 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ASTRAL.NS 195 41 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ATUL.NS 195 42 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AUROPHARMA.NS 195 43 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AVANTIFEED.NS 195 44 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DMART.NS 195 45 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
AXISBANK.NS 195 46 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BASF.NS 195 47 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BEML.NS 195 48 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BLS.NS 195 49 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BSE.NS 195 50 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAJAJ-AUTO.NS 195 51 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAJAJELEC.NS 195 52 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAJFINANCE.NS 195 53 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAJAJFINSV.NS 195 54 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAJAJHLDNG.NS 195 55 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BALAMINES.NS 195 56 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BALKRISIND.NS 195 57 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BALRAMCHIN.NS 195 58 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BANDHANBNK.NS 195 59 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BANKBARODA.NS 195 60 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BANKINDIA.NS 195 61 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAHABANK.NS 195 62 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BATAINDIA.NS 195 63 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BAYERCROP.NS 195 64 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BERGEPAINT.NS 195 65 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BDL.NS 195 66 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BEL.NS 195 67 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BHARATFORG.NS 195 68 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BHEL.NS 195 69 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BPCL.NS 195 70 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BHARTIARTL.NS 195 71 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
skipping BIKAJI.NS as it has only 109 values
[*********************100%***********************]  1 of 1 completed
BIOCON.NS 195 72 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BIRLACORPN.NS 195 73 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BSOFT.NS 195 74 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BLUEDART.NS 195 75 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BLUESTARCO.NS 195 76 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BBTC.NS 195 77 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BORORENEW.NS 195 78 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BOSCHLTD.NS 195 79 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BRIGADE.NS 195 80 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BCG.NS 195 81 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
BRITANNIA.NS 195 82 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAPMYINDIA.NS 195 83 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CCL.NS 195 84 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CESC.NS 195 85 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CGPOWER.NS 195 86 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CRISIL.NS 195 87 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CSBBANK.NS 195 88 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CAMPUS.NS 195 89 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CANFINHOME.NS 195 90 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CANBK.NS 195 91 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CGCL.NS 195 92 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CARBORUNIV.NS 195 93 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CASTROLIND.NS 195 94 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CEATLTD.NS 195 95 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CENTRALBK.NS 195 96 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CDSL.NS 195 97 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CENTURYPLY.NS 195 98 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CENTURYTEX.NS 195 99 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CERA.NS 195 100 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CHALET.NS 195 101 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CHAMBLFERT.NS 195 102 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CHEMPLASTS.NS 195 103 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CHOLAHLDNG.NS 195 104 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CHOLAFIN.NS 195 105 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CIPLA.NS 195 106 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CUB.NS 195 107 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CLEAN.NS 195 108 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
COALINDIA.NS 195 109 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
COCHINSHIP.NS 195 110 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
COFORGE.NS 195 111 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
COLPAL.NS 195 112 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CAMS.NS 195 113 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CONCOR.NS 195 114 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
COROMANDEL.NS 195 115 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CRAFTSMAN.NS 195 116 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CREDITACC.NS 195 117 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CROMPTON.NS 195 118 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CUMMINSIND.NS 195 119 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
CYIENT.NS 195 120 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DCMSHRIRAM.NS 195 121 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DLF.NS 195 122 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DABUR.NS 195 123 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DALBHARAT.NS 195 124 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DATAPATTNS.NS 195 125 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DEEPAKFERT.NS 195 126 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DEEPAKNTR.NS 195 127 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DELHIVERY.NS 195 128 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DELTACORP.NS 195 129 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DEVYANI.NS 195 130 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DIVISLAB.NS 195 131 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DIXON.NS 195 132 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LALPATHLAB.NS 195 133 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
DRREDDY.NS 195 134 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EIDPARRY.NS 195 135 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EIHOTEL.NS 195 136 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EPL.NS 195 137 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EASEMYTRIP.NS 195 138 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EDELWEISS.NS 195 139 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EICHERMOT.NS 195 140 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ELGIEQUIP.NS 195 141 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
EMAMILTD.NS 195 142 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ENDURANCE.NS 195 143 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ENGINERSIN.NS 195 144 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EQUITASBNK.NS 195 145 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ESCORTS.NS 195 146 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
EXIDEIND.NS 195 147 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FDC.NS 195 148 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NYKAA.NS 195 149 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FEDERALBNK.NS 195 150 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FACT.NS 195 151 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FINEORG.NS 195 152 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FINCABLES.NS 195 153 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FINPIPE.NS 195 154 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FSL.NS 195 155 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping FIVESTAR.NS as it has only 106 values
[*********************100%***********************]  1 of 1 completed
FORTIS.NS 195 156 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GRINFRA.NS 195 157 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GAIL.NS 195 158 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GMMPFAUDLR.NS 195 159 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GMRINFRA.NS 195 160 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GALAXYSURF.NS 195 161 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GARFIBRES.NS 195 162 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GICRE.NS 195 163 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GLAND.NS 195 164 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GLAXO.NS 195 165 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GLENMARK.NS 195 166 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping MEDANTA.NS as it has only 107 values
[*********************100%***********************]  1 of 1 completed
GOCOLORS.NS 195 167 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GODFRYPHLP.NS 195 168 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GODREJAGRO.NS 195 169 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GODREJCP.NS 195 170 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GODREJIND.NS 195 171 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GODREJPROP.NS 195 172 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GRANULES.NS 195 173 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GRAPHITE.NS 195 174 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GRASIM.NS 195 175 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GESHIP.NS 195 176 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GREENPANEL.NS 195 177 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GRINDWELL.NS 195 178 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GUJALKALI.NS 195 179 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GAEL.NS 195 180 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
FLUOROCHEM.NS 195 181 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GUJGASLTD.NS 195 182 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GNFC.NS 195 183 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GPPL.NS 195 184 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GSFC.NS 195 185 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
GSPL.NS 195 186 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HEG.NS 195 187 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HCLTECH.NS 195 188 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HDFCAMC.NS 195 189 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HDFCBANK.NS 195 190 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HDFCLIFE.NS 195 191 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HFCL.NS 195 192 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HLEGLAS.NS 195 193 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HAPPSTMNDS.NS 195 194 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HAVELLS.NS 195 195 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HEROMOTOCO.NS 195 196 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HIKAL.NS 195 197 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HINDALCO.NS 195 198 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HGS.NS 195 199 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HAL.NS 195 200 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HINDCOPPER.NS 195 201 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HINDPETRO.NS 195 202 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HINDUNILVR.NS 195 203 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HINDZINC.NS 195 204 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POWERINDIA.NS 195 205 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HOMEFIRST.NS 195 206 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HONAUT.NS 195 207 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HUDCO.NS 195 208 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
HDFC.NS 195 209 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ICICIBANK.NS 195 210 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
ICICIGI.NS 195 211 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ICICIPRULI.NS 195 212 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ISEC.NS 195 213 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IDBI.NS 195 214 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IDFCFIRSTB.NS 195 215 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IDFC.NS 195 216 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IFBIND.NS 195 217 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IIFL.NS 195 218 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IRB.NS 195 219 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ITC.NS 195 220 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ITI.NS 195 221 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDIACEM.NS 195 222 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IBULHSGFIN.NS 195 223 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IBREALEST.NS 195 224 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDIAMART.NS 195 225 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDIANB.NS 195 226 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IEX.NS 195 227 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDHOTEL.NS 195 228 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IOC.NS 195 229 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IOB.NS 195 230 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IRCTC.NS 195 231 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IRFC.NS 195 232 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDIGOPNTS.NS 195 233 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IGL.NS 195 234 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDUSTOWER.NS 195 235 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDUSINDBK.NS 195 236 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INFIBEAM.NS 195 237 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NAUKRI.NS 195 238 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INFY.NS 195 239 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INGERRAND.NS 195 240 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INTELLECT.NS 195 241 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
INDIGO.NS 195 242 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IPCALAB.NS 195 243 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JBCHEPHARM.NS 195 244 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JKCEMENT.NS 195 245 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JBMA.NS 195 246 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JKLAKSHMI.NS 195 247 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JKPAPER.NS 195 248 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JMFINANCIL.NS 195 249 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JSWENERGY.NS 195 250 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JSWSTEEL.NS 195 251 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JAMNAAUTO.NS 195 252 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JSL.NS 195 253 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JINDALSTEL.NS 195 254 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JINDWORLD.NS 195 255 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JUBLFOOD.NS 195 256 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JUBLINGREA.NS 195 257 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JUBLPHARMA.NS 195 258 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JUSTDIAL.NS 195 259 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
JYOTHYLAB.NS 195 260 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KPRMILL.NS 195 261 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KEI.NS 195 262 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KNRCON.NS 195 263 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KPITTECH.NS 195 264 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KRBL.NS 195 265 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KSB.NS 195 266 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KAJARIACER.NS 195 267 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KALPATPOWR.NS 195 268 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KALYANKJIL.NS 195 269 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KANSAINER.NS 195 270 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KARURVYSYA.NS 195 271 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KEC.NS 195 272 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KENNAMET.NS 195 273 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping RUSTOMJEE.NS as it has only 103 values
[*********************100%***********************]  1 of 1 completed
skipping KFINTECH.NS as it has only 78 values
[*********************100%***********************]  1 of 1 completed
KOTAKBANK.NS 195 274 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
KIMS.NS 195 275 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
L&TFH.NS 195 276 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LTTS.NS 195 277 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LICHSGFIN.NS 195 278 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LTIM.NS 195 279 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
LAXMIMACH.NS 195 280 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LT.NS 195 281 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LATENTVIEW.NS 195 282 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LAURUSLABS.NS 195 283 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LXCHEM.NS 195 284 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LEMONTREE.NS 195 285 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LICI.NS 195 286 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LINDEINDIA.NS 195 287 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LUPIN.NS 195 288 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LUXIND.NS 195 289 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MMTC.NS 195 290 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MRF.NS 195 291 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MTARTECH.NS 195 292 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
LODHA.NS 195 293 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MGL.NS 195 294 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
M&MFIN.NS 195 295 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
M&M.NS 195 296 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAHINDCIE.NS 195 297 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MHRIL.NS 195 298 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAHLIFE.NS 195 299 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAHLOG.NS 195 300 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MANAPPURAM.NS 195 301 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MRPL.NS 195 302 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MARICO.NS 195 303 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MARUTI.NS 195 304 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MASTEK.NS 195 305 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MFSL.NS 195 306 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAXHEALTH.NS 195 307 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MAZDOCK.NS 195 308 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MEDPLUS.NS 195 309 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MFL.NS 195 310 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
METROBRAND.NS 195 311 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
METROPOLIS.NS 195 312 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MSUMI.NS 195 313 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MOTILALOFS.NS 195 314 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MPHASIS.NS 195 315 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MCX.NS 195 316 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MUTHOOTFIN.NS 195 317 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NATCOPHARM.NS 195 318 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NBCC.NS 195 319 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NCC.NS 195 320 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NHPC.NS 195 321 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NLCINDIA.NS 195 322 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NMDC.NS 195 323 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NOCIL.NS 195 324 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NTPC.NS 195 325 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NH.NS 195 326 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NATIONALUM.NS 195 327 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NAVINFLUOR.NS 195 328 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NAZARA.NS 195 329 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NESTLEIND.NS 195 330 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NETWORK18.NS 195 331 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NAM-INDIA.NS 195 332 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NUVOCO.NS 195 333 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
OBEROIRLTY.NS 195 334 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ONGC.NS 195 335 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
OIL.NS 195 336 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
OLECTRA.NS 195 337 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PAYTM.NS 195 338 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
OFSS.NS 195 339 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ORIENTELEC.NS 195 340 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POLICYBZR.NS 195 341 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PCBL.NS 195 342 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PIIND.NS 195 343 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PNBHOUSING.NS 195 344 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PNCINFRA.NS 195 345 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PVR.NS 195 346 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PAGEIND.NS 195 347 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PATANJALI.NS 195 348 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PERSISTENT.NS 195 349 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PETRONET.NS 195 350 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
PFIZER.NS 195 351 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PHOENIXLTD.NS 195 352 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PIDILITIND.NS 195 353 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PEL.NS 195 354 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping PPLPHARMA.NS as it has only 127 values
[*********************100%***********************]  1 of 1 completed
POLYMED.NS 195 355 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POLYCAB.NS 195 356 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POLYPLEX.NS 195 357 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POONAWALLA.NS 195 358 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PFC.NS 195 359 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
POWERGRID.NS 195 360 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PRAJIND.NS 195 361 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PRESTIGE.NS 195 362 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PRINCEPIPE.NS 195 363 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PRSMJOHNSN.NS 195 364 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PGHH.NS 195 365 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
PNB.NS 195 366 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
QUESS.NS 195 367 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RBLBANK.NS 195 368 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RECLTD.NS 195 369 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RHIM.NS 195 370 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RITES.NS 195 371 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RADICO.NS 195 372 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RVNL.NS 195 373 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RAIN.NS 195 374 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RAINBOW.NS 195 375 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RAJESHEXPO.NS 195 376 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RALLIS.NS 195 377 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RCF.NS 195 378 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RATNAMANI.NS 195 379 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RTNINDIA.NS 195 380 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RAYMOND.NS 195 381 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
REDINGTON.NS 195 382 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RELAXO.NS 195 383 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RELIANCE.NS 195 384 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RBA.NS 195 385 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ROSSARI.NS 195 386 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ROUTE.NS 195 387 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SBICARD.NS 195 388 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SBILIFE.NS 195 389 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SJVN.NS 195 390 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SKFINDIA.NS 195 391 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SRF.NS 195 392 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MOTHERSON.NS 195 393 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SANOFI.NS 195 394 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SAPPHIRE.NS 195 395 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SCHAEFFLER.NS 195 396 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SHARDACROP.NS 195 397 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SHOPERSTOP.NS 195 398 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SHREECEM.NS 195 399 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RENUKA.NS 195 400 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SHRIRAMFIN.NS 195 401 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SHYAMMETL.NS 195 402 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SIEMENS.NS 195 403 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SOBHA.NS 195 404 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SOLARINDS.NS 195 405 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SONACOMS.NS 195 406 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SONATSOFTW.NS 195 407 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
STARHEALTH.NS 195 408 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SBIN.NS 195 409 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SAIL.NS 195 410 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SWSOLAR.NS 195 411 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
STLTECH.NS 195 412 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUMICHEM.NS 195 413 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SPARC.NS 195 414 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUNPHARMA.NS 195 415 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUNTV.NS 195 416 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUNDARMFIN.NS 195 417 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUNDRMFAST.NS 195 418 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUNTECK.NS 195 419 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUPRAJIT.NS 195 420 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
SUPREMEIND.NS 195 421 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUVENPHAR.NS 195 422 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SUZLON.NS 195 423 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SWANENERGY.NS 195 424 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
SYNGENE.NS 195 425 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TCIEXP.NS 195 426 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TCNSBRANDS.NS 195 427 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TTKPRESTIG.NS 195 428 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TV18BRDCST.NS 195 429 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TVSMOTOR.NS 195 430 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
skipping TMB.NS as it has only 150 values
[*********************100%***********************]  1 of 1 completed
TANLA.NS 195 431 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATACHEM.NS 195 432 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATACOMM.NS 195 433 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TCS.NS 195 434 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATACONSUM.NS 195 435 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATAELXSI.NS 195 436 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATAINVEST.NS 195 437 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATAMTRDVR.NS 195 438 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATAMOTORS.NS 195 439 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATAPOWER.NS 195 440 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TATASTEEL.NS 195 441 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TTML.NS 195 442 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TEAMLEASE.NS 195 443 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TECHM.NS 195 444 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TEJASNET.NS 195 445 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
NIACL.NS 195 446 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
RAMCOCEM.NS 195 447 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
THERMAX.NS 195 448 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TIMKEN.NS 195 449 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TITAN.NS 195 450 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TORNTPHARM.NS 195 451 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TORNTPOWER.NS 195 452 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TCI.NS 195 453 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TRENT.NS 195 454 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TRIDENT.NS 195 455 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TRIVENI.NS 195 456 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TRITURBINE.NS 195 457 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
TIINDIA.NS 195 458 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UCOBANK.NS 195 459 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UFLEX.NS 195 460 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UNOMINDA.NS 195 461 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UPL.NS 195 462 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UTIAMC.NS 195 463 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ULTRACEMCO.NS 195 464 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UNIONBANK.NS 195 465 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
UBL.NS 195 466 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MCDOWELL-N.NS 195 467 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VGUARD.NS 195 468 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VMART.NS 195 469 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VIPIND.NS 195 470 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VAIBHAVGBL.NS 195 471 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VTL.NS 195 472 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VARROC.NS 195 473 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VBL.NS 195 474 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
MANYAVAR.NS 195 475 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VEDL.NS 195 476 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VIJAYA.NS 195 477 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VINATIORGA.NS 195 478 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
IDEA.NS 195 479 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
VOLTAS.NS 195 480 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
WELCORP.NS 195 481 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
WELSPUNIND.NS 195 482 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
WESTLIFE.NS 195 483 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
WHIRLPOOL.NS 195 484 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
WIPRO.NS 195 485 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
YESBANK.NS 195 486 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ZFCVINDIA.NS 195 487 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ZEEL.NS 195 488 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ZENSARTECH.NS 195 489 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ZOMATO.NS 195 490 out of 500 stocks imported

[*********************100%***********************]  1 of 1 completed
ZYDUSLIFE.NS 195 491 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ZYDUSWELL.NS 195 492 out of 500 stocks imported
[*********************100%***********************]  1 of 1 completed
ECLERX.NS 195 493 out of 500 stocks imported

In [5]:
nifty_500.head()

           Company Name                Industry   Symbol Series     ISIN Code
0      360 ONE WAM Ltd.      Financial Services   360ONE     EQ  INE466L01038
1         3M India Ltd.             Diversified  3MINDIA     EQ  INE470A01017
2        ABB India Ltd.           Capital Goods      ABB     EQ  INE117A01022
3              ACC Ltd.  Construction Materials      ACC     EQ  INE012A01025
4  AIA Engineering Ltd.           Capital Goods   AIAENG     EQ  INE212H01026

In [6]:
data_dump = pd.DataFrame(data['ABB.NS'])

data_dump.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-07-11,2600.000000,2630.000000,2576.100098,2610.850098,2610.850098,187883
2022-07-12,2607.000000,2609.000000,2529.100098,2540.800049,2540.800049,204632
2022-07-13,2542.000000,2572.250000,2515.000000,2544.699951,2544.699951,187311
2022-07-14,2544.000000,2571.000000,2502.699951,2548.350098,2548.350098,204252
2022-07-15,2530.100098,2575.149902,2521.000000,2559.449951,2559.449951,389496

In [7]:
data

{'360ONE.NS':                   Open        High         Low       Close   Adj Close  Volume
 Date
 2022-07-11  388.375000  396.924988  387.087494  392.862488  382.148407   88672
 2022-07-12  390.987488  400.750000  390.987488  398.950012  388.069885   69144
 2022-07-13  402.537506  406.612488  393.287506  396.487488  385.674530   49572
 2022-07-14  399.962494  400.700012  387.887512  390.587494  379.935425   59224
 2022-07-15  385.000000  391.774994  385.000000  389.875000  379.242371   26324
 ...                ...         ...         ...         ...         ...     ...
 2023-04-19  411.299988  417.850006  403.649994  415.100006  415.100006  534435
 2023-04-20  416.000000  416.899994  408.899994  409.850006  409.850006  183907
 2023-04-21  409.850006  412.200012  404.250000  407.000000  407.000000  146745
 2023-04-24  412.250000  416.950012  407.000000  415.950012  415.950012  141834
 2023-04-25  415.950012  418.750000  412.899994  415.899994  415.899994  259300

 [195 rows x 6 columns],
 '3MINDIA.NS':                     Open          High           Low         Close  \
 Date
 2022-07-11  22701.000000  23000.000000  22600.050781  22869.750000
 2022-07-12  22750.000000  23125.000000  22685.349609  22938.050781
 2022-07-13  22951.000000  23212.199219  22881.000000  22887.400391
 2022-07-14  23000.000000  23000.000000  22564.900391  22700.250000
 2022-07-15  22725.000000  22961.050781  21510.050781  21928.349609
 ...                  ...           ...           ...           ...
 2023-04-19  22919.000000  22978.949219  22700.000000  22777.449219
 2023-04-20  22878.000000  22878.000000  22540.000000  22627.849609
 2023-04-21  22658.900391  22714.699219  22300.000000  22347.900391
 2023-04-24  22400.000000  22765.500000  22125.250000  22412.949219
 2023-04-25  22382.949219  22800.000000  22160.750000  22296.199219

                Adj Close  Volume
 Date
 2022-07-11  22070.306641    1564
 2022-07-12  22136.220703    1876
 2022-07-13  22087.339844    2040
 2022-07-14  21906.732422    1945
 2022-07-15  21161.814453    7380
 ...                  ...     ...
 2023-04-19  22777.449219     970
 2023-04-20  22627.849609    3268
 2023-04-21  22347.900391    1055
 2023-04-24  22412.949219    6232
 2023-04-25  22296.199219   23477

 [195 rows x 6 columns],
 'ABB.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2600.000000  2630.000000  2576.100098  2610.850098  2610.850098
 2022-07-12  2607.000000  2609.000000  2529.100098  2540.800049  2540.800049
 2022-07-13  2542.000000  2572.250000  2515.000000  2544.699951  2544.699951
 2022-07-14  2544.000000  2571.000000  2502.699951  2548.350098  2548.350098
 2022-07-15  2530.100098  2575.149902  2521.000000  2559.449951  2559.449951
 ...                 ...          ...          ...          ...          ...
 2023-04-19  3213.000000  3243.000000  3186.050049  3201.050049  3201.050049
 2023-04-20  3212.000000  3231.750000  3178.000000  3184.300049  3184.300049
 2023-04-21  3198.000000  3212.550049  3141.149902  3153.300049  3153.300049
 2023-04-24  3164.699951  3232.000000  3160.649902  3217.399902  3217.399902
 2023-04-25  3228.000000  3355.000000  3210.050049  3336.100098  3336.100098

             Volume
 Date
 2022-07-11  187883
 2022-07-12  204632
 2022-07-13  187311
 2022-07-14  204252
 2022-07-15  389496
 ...            ...
 2023-04-19  266982
 2023-04-20  276392
 2023-04-21  267054
 2023-04-24  314556
 2023-04-25  690245

 [195 rows x 6 columns],
 'ACC.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2164.399902  2191.800049  2136.899902  2184.300049  2184.300049
 2022-07-12  2181.000000  2182.600098  2156.000000  2167.250000  2167.250000
 2022-07-13  2177.000000  2186.899902  2164.000000  2173.550049  2173.550049
 2022-07-14  2178.000000  2191.149902  2148.000000  2160.300049  2160.300049
 2022-07-15  2132.050049  2159.000000  2111.000000  2140.350098  2140.350098
 ...                 ...          ...          ...          ...          ...
 2023-04-19  1765.000000  1775.849976  1742.849976  1749.300049  1749.300049
 2023-04-20  1750.000000  1758.900024  1735.000000  1738.099976  1738.099976
 2023-04-21  1741.949951  1744.800049  1712.750000  1717.949951  1717.949951
 2023-04-24  1719.900024  1740.000000  1710.300049  1734.650024  1734.650024
 2023-04-25  1735.000000  1751.000000  1726.750000  1736.150024  1736.150024

              Volume
 Date
 2022-07-11   282881
 2022-07-12   261604
 2022-07-13   218371
 2022-07-14   245807
 2022-07-15  1004798
 ...             ...
 2023-04-19   372749
 2023-04-20   256370
 2023-04-21   346777
 2023-04-24   258999
 2023-04-25   258998

 [195 rows x 6 columns],
 'AIAENG.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2338.000000  2349.000000  2269.899902  2303.699951  2295.801758
 2022-07-12  2299.800049  2340.000000  2267.899902  2332.350098  2324.353516
 2022-07-13  2334.199951  2335.600098  2251.250000  2264.899902  2257.134766
 2022-07-14  2268.050049  2328.750000  2243.250000  2316.750000  2308.806885
 2022-07-15  2322.000000  2344.949951  2285.000000  2301.300049  2293.409912
 ...                 ...          ...          ...          ...          ...
 2023-04-19  2787.850098  2817.000000  2732.600098  2745.800049  2745.800049
 2023-04-20  2759.949951  2780.000000  2734.000000  2746.199951  2746.199951
 2023-04-21  2754.000000  2804.899902  2750.000000  2779.800049  2779.800049
 2023-04-24  2779.949951  2820.050049  2712.050049  2727.899902  2727.899902
 2023-04-25  2741.949951  2766.399902  2678.850098  2689.500000  2689.500000

             Volume
 Date
 2022-07-11   71259
 2022-07-12   40298
 2022-07-13  263943
 2022-07-14  141751
 2022-07-15   57425
 ...            ...
 2023-04-19   62438
 2023-04-20   44180
 2023-04-21   50559
 2023-04-24  112380
 2023-04-25   68130

 [195 rows x 6 columns],
 'APLAPOLLO.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11   874.349976   895.000000   865.000000   889.250000   886.222534
 2022-07-12   882.000000   882.000000   856.400024   859.650024   856.723328
 2022-07-13   859.650024   889.000000   859.650024   869.599976   866.639404
 2022-07-14   873.900024   880.000000   850.049988   861.099976   858.168335
 2022-07-15   862.900024   876.400024   858.200012   869.700012   866.739136
 ...                 ...          ...          ...          ...          ...
 2023-04-19  1235.949951  1248.000000  1228.000000  1230.150024  1230.150024
 2023-04-20  1234.000000  1251.750000  1213.000000  1225.099976  1225.099976
 2023-04-21  1231.400024  1240.000000  1211.349976  1230.050049  1230.050049
 2023-04-24  1230.050049  1238.099976  1215.250000  1220.699951  1220.699951
 2023-04-25  1228.550049  1229.949951  1213.500000  1219.000000  1219.000000

             Volume
 Date
 2022-07-11  253222
 2022-07-12  257240
 2022-07-13  183089
 2022-07-14  146211
 2022-07-15   84651
 ...            ...
 2023-04-19  263474
 2023-04-20  284286
 2023-04-21  178329
 2023-04-24  287482
 2023-04-25  485132

 [195 rows x 6 columns],
 'AUBANK.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2022-07-11  580.000000  591.750000  576.200012  584.650024  584.147644
 2022-07-12  583.450012  587.750000  574.150024  577.000000  576.504150
 2022-07-13  579.900024  584.900024  566.750000  571.150024  570.659241
 2022-07-14  568.650024  571.150024  550.349976  554.500000  554.023499
 2022-07-15  555.000000  558.950012  539.000000  550.150024  549.677246
 ...                ...         ...         ...         ...         ...
 2023-04-19  694.000000  699.000000  674.450012  678.599976  678.599976
 2023-04-20  682.000000  685.000000  674.099976  679.400024  679.400024
 2023-04-21  680.450012  680.849976  656.849976  665.950012  665.950012
 2023-04-24  662.000000  669.750000  658.650024  663.900024  663.900024
 2023-04-25  667.000000  667.750000  658.549988  660.150024  660.150024

              Volume
 Date
 2022-07-11  1197204
 2022-07-12  1415638
 2022-07-13   889964
 2022-07-14  2573264
 2022-07-15  2026203
 ...             ...
 2023-04-19  3693818
 2023-04-20  1555616
 2023-04-21  3742874
 2023-04-24  2852500
 2023-04-25  2107327

 [195 rows x 6 columns],
 'AARTIDRUGS.NS':                   Open        High         Low       Close   Adj Close  Volume
 Date
 2022-07-11  403.000000  420.200012  400.850006  418.500000  417.436188  146293
 2022-07-12  420.200012  430.350006  415.000000  420.700012  419.630615   94985
 2022-07-13  420.700012  424.500000  415.600006  417.649994  416.588348   42753
 2022-07-14  425.000000  445.600006  419.700012  434.149994  433.046417  116557
 2022-07-15  441.000000  441.500000  433.000000  437.899994  436.786865  114912
 ...                ...         ...         ...         ...         ...     ...
 2023-04-19  425.100006  436.000000  413.049988  426.200012  426.200012  966281
 2023-04-20  428.950012  434.200012  421.000000  426.649994  426.649994  542124
 2023-04-21  427.149994  428.899994  415.000000  423.250000  423.250000  238423
 2023-04-24  423.899994  426.149994  416.100006  420.649994  420.649994  209088
 2023-04-25  420.000000  428.500000  416.350006  420.850006  420.850006  185068

 [195 rows x 6 columns],
 'AARTIIND.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2022-07-11  726.000000  747.700012  715.799988  744.200012  741.588989
 2022-07-12  743.950012  747.900024  726.599976  728.849976  726.292786
 2022-07-13  732.400024  740.000000  729.799988  734.400024  731.823364
 2022-07-14  738.099976  744.000000  716.549988  726.250000  723.701904
 2022-07-15  728.750000  732.900024  719.750000  728.400024  725.844421
 ...                ...         ...         ...         ...         ...
 2023-04-19  549.950012  554.000000  542.950012  544.849976  544.849976
 2023-04-20  547.400024  549.150024  542.650024  544.099976  544.099976
 2023-04-21  547.549988  558.400024  538.200012  555.349976  555.349976
 2023-04-24  555.549988  559.150024  548.000000  550.500000  550.500000
 2023-04-25  550.400024  556.900024  546.200012  552.349976  552.349976

              Volume
 Date
 2022-07-11  1353022
 2022-07-12   904935
 2022-07-13   441553
 2022-07-14   400938
 2022-07-15   490338
 ...             ...
 2023-04-19   266589
 2023-04-20   175258
 2023-04-21   675335
 2023-04-24   426732
 2023-04-25   423172

 [195 rows x 6 columns],
 'AAVAS.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  1975.000000  2040.000000  1965.050049  2021.599976  2021.599976
 2022-07-12  2016.000000  2016.000000  1981.000000  1995.800049  1995.800049
 2022-07-13  1995.800049  2050.000000  1973.000000  2020.500000  2020.500000
 2022-07-14  2020.900024  2020.900024  1941.000000  1959.800049  1959.800049
 2022-07-15  1955.099976  1999.000000  1955.099976  1992.449951  1992.449951
 ...                 ...          ...          ...          ...          ...
 2023-04-19  1742.800049  1774.900024  1740.099976  1759.699951  1759.699951
 2023-04-20  1762.000000  1762.000000  1662.000000  1668.099976  1668.099976
 2023-04-21  1675.000000  1675.000000  1562.099976  1579.000000  1579.000000
 2023-04-24  1590.900024  1599.000000  1543.050049  1558.050049  1558.050049
 2023-04-25  1558.000000  1585.900024  1505.000000  1516.449951  1516.449951

             Volume
 Date
 2022-07-11   31996
 2022-07-12   45878
 2022-07-13   90770
 2022-07-14   79012
 2022-07-15   44842
 ...            ...
 2023-04-19  259321
 2023-04-20  601144
 2023-04-21  320721
 2023-04-24  179594
 2023-04-25  232659

 [195 rows x 6 columns],
 'ABBOTINDIA.NS':                     Open          High           Low         Close  \
 Date
 2022-07-11  19450.000000  19666.000000  19306.400391  19344.400391
 2022-07-12  19300.000000  19574.099609  19180.199219  19463.199219
 2022-07-13  19687.000000  19687.000000  19324.949219  19557.500000
 2022-07-14  19557.500000  19860.000000  19255.000000  19478.199219
 2022-07-15  19585.650391  19779.949219  19510.050781  19746.949219
 ...                  ...           ...           ...           ...
 2023-04-19  22679.949219  22919.949219  22550.000000  22733.750000
 2023-04-20  22733.949219  22823.949219  22548.550781  22577.750000
 2023-04-21  22600.000000  22643.949219  22232.050781  22434.699219
 2023-04-24  22440.000000  22589.949219  22274.000000  22546.300781
 2023-04-25  22590.000000  22660.000000  22260.050781  22301.849609

                Adj Close  Volume
 Date
 2022-07-11  19100.144531    6205
 2022-07-12  19217.441406    8572
 2022-07-13  19310.552734    8425
 2022-07-14  19232.253906   10608
 2022-07-15  19497.609375    6942
 ...                  ...     ...
 2023-04-19  22733.750000   22685
 2023-04-20  22577.750000    6245
 2023-04-21  22434.699219    8120
 2023-04-24  22546.300781    4653
 2023-04-25  22301.849609   10076

 [195 rows x 6 columns],
 'ADANIENT.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2293.050049  2384.600098  2291.050049  2373.250000  2372.241455
 2022-07-12  2364.399902  2389.800049  2350.149902  2365.649902  2364.644775
 2022-07-13  2373.500000  2384.649902  2333.699951  2353.500000  2352.500000
 2022-07-14  2365.000000  2404.000000  2336.500000  2383.100098  2383.100098
 2022-07-15  2414.500000  2422.949951  2377.000000  2405.250000  2405.250000
 ...                 ...          ...          ...          ...          ...
 2023-04-19  1847.000000  1877.699951  1835.000000  1853.849976  1853.849976
 2023-04-20  1855.000000  1878.900024  1836.849976  1842.900024  1842.900024
 2023-04-21  1846.000000  1853.250000  1796.050049  1803.000000  1803.000000
 2023-04-24  1804.000000  1817.400024  1775.800049  1801.949951  1801.949951
 2023-04-25  1806.000000  1913.750000  1801.800049  1844.599976  1844.599976

              Volume
 Date
 2022-07-11  1967308
 2022-07-12  1273008
 2022-07-13   982185
 2022-07-14   933554
 2022-07-15  1169788
 ...             ...
 2023-04-19  2455884
 2023-04-20  2016823
 2023-04-21  2090833
 2023-04-24  1963582
 2023-04-25  5364841

 [195 rows x 6 columns],
 'ADANIGREEN.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  1918.500000  2263.649902  1910.800049  2207.350098  2207.350098
 2022-07-12  2229.949951  2374.000000  2224.149902  2294.750000  2294.750000
 2022-07-13  2328.000000  2384.000000  2085.000000  2104.750000  2104.750000
 2022-07-14  2160.000000  2188.000000  1931.000000  2087.000000  2087.000000
 2022-07-15  2115.050049  2175.000000  2024.199951  2072.649902  2072.649902
 ...                 ...          ...          ...          ...          ...
 2023-04-19   952.400024   955.000000   920.500000   935.799988   935.799988
 2023-04-20   937.000000   948.900024   925.000000   933.049988   933.049988
 2023-04-21   937.000000   938.000000   911.299988   916.200012   916.200012
 2023-04-24   916.200012   916.250000   880.000000   887.099976   887.099976
 2023-04-25   870.000000   931.450012   864.900024   931.150024   931.150024

               Volume
 Date
 2022-07-11   7833061
 2022-07-12   8095252
 2022-07-13   6661674
 2022-07-14   8953549
 2022-07-15  16301850
 ...              ...
 2023-04-19   1177133
 2023-04-20   1181812
 2023-04-21    727246
 2023-04-24   1450872
 2023-04-25   2314534

 [195 rows x 6 columns],
 'ADANIPORTS.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2022-07-11  715.000000  732.000000  713.049988  729.200012  724.183167
 2022-07-12  729.000000  742.900024  726.349976  731.900024  726.864624
 2022-07-13  737.049988  739.000000  724.349976  726.750000  721.750000
 2022-07-14  729.000000  730.799988  716.549988  724.450012  724.450012
 2022-07-15  737.700012  738.450012  726.099976  730.900024  730.900024
 ...                ...         ...         ...         ...         ...
 2023-04-19  659.000000  665.000000  654.900024  658.400024  658.400024
 2023-04-20  663.000000  678.500000  661.200012  666.099976  666.099976
 2023-04-21  668.000000  670.599976  658.650024  661.599976  661.599976
 2023-04-24  665.099976  672.750000  656.000000  671.299988  671.299988
 2023-04-25  675.000000  682.500000  668.849976  671.450012  671.450012

              Volume
 Date
 2022-07-11  3814715
 2022-07-12  5846548
 2022-07-13  2373553
 2022-07-14  2859869
 2022-07-15  4127381
 ...             ...
 2023-04-19  2683546
 2023-04-20  5009410
 2023-04-21  1982614
 2023-04-24  3357178
 2023-04-25  4814190

 [195 rows x 6 columns],
 'ADANIPOWER.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2022-07-11  270.000000  285.100006  269.250000  285.100006  285.100006
 2022-07-12  286.799988  299.350006  286.049988  292.750000  292.750000
 2022-07-13  298.399994  299.600006  285.000000  286.649994  286.649994
 2022-07-14  288.000000  289.799988  277.000000  283.700012  283.700012
 2022-07-15  286.000000  287.950012  283.250000  286.750000  286.750000
 ...                ...         ...         ...         ...         ...
 2023-04-19  188.800003  189.449997  185.199997  187.300003  187.300003
 2023-04-20  188.500000  196.649994  187.000000  195.800003  195.800003
 2023-04-21  200.000000  200.500000  193.600006  199.250000  199.250000
 2023-04-24  199.000000  203.399994  194.399994  201.399994  201.399994
 2023-04-25  201.000000  210.399994  200.000000  205.649994  205.649994

               Volume
 Date
 2022-07-11  14086766
 2022-07-12  22402570
 2022-07-13   8566423
 2022-07-14   6997656
 2022-07-15   4462588
 ...              ...
 2023-04-19   3119628
 2023-04-20  11055623
 2023-04-21  11239848
 2023-04-24   6274761
 2023-04-25  11876735

 [195 rows x 6 columns],
 'ATGL.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2550.000000  2775.000000  2502.149902  2716.649902  2716.395752
 2022-07-12  2690.000000  2844.949951  2685.050049  2797.550049  2797.288330
 2022-07-13  2830.000000  2867.500000  2646.000000  2672.100098  2671.850098
 2022-07-14  2689.000000  2832.000000  2601.000000  2764.850098  2764.850098
 2022-07-15  2800.000000  2847.649902  2731.050049  2807.699951  2807.699951
 ...                 ...          ...          ...          ...          ...
 2023-04-19   954.400024   954.400024   924.000000   930.349976   930.349976
 2023-04-20   932.000000   939.000000   920.700012   928.200012   928.200012
 2023-04-21   931.799988   932.000000   908.000000   917.799988   917.799988
 2023-04-24   919.000000   922.849976   889.000000   891.150024   891.150024
 2023-04-25   895.000000   935.700012   890.000000   935.250000   935.250000

             Volume
 Date
 2022-07-11  974385
 2022-07-12  931697
 2022-07-13  715239
 2022-07-14  592269
 2022-07-15  572560
 ...            ...
 2023-04-19  531461
 2023-04-20  346506
 2023-04-21  314017
 2023-04-24  384326
 2023-04-25  730197

 [195 rows x 6 columns],
 'ADANITRANS.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2022-07-11  2545.000000  2753.149902  2531.300049  2690.949951  2690.949951
 2022-07-12  2667.000000  2812.000000  2640.000000  2749.800049  2749.800049
 2022-07-13  2773.000000  2801.100098  2620.550049  2730.800049  2730.800049
 2022-07-14  2752.000000  2965.000000  2711.199951  2889.149902  2889.149902
 2022-07-15  2970.399902  3015.000000  2841.100098  2889.350098  2889.350098
 ...                 ...          ...          ...          ...          ...
 2023-04-19  1038.750000  1038.750000  1005.000000  1017.700012  1017.700012
 2023-04-20  1020.000000  1025.000000  1007.049988  1011.099976  1011.099976
 2023-04-21  1012.500000  1016.799988   985.099976   994.900024   994.900024
 2023-04-24   998.950012   999.000000   960.400024   965.099976   965.099976

In [8]:
data['360ONE.NS'].shape

(195, 6)

In [9]:
data['360ONE.NS'].head()

                  Open        High         Low       Close   Adj Close  Volume
Date
2022-07-11  388.375000  396.924988  387.087494  392.862488  382.148407   88672
2022-07-12  390.987488  400.750000  390.987488  398.950012  388.069885   69144
2022-07-13  402.537506  406.612488  393.287506  396.487488  385.674530   49572
2022-07-14  399.962494  400.700012  387.887512  390.587494  379.935425   59224
2022-07-15  385.000000  391.774994  385.000000  389.875000  379.242371   26324

In [10]:
datetime.date.today()

datetime.date(2023, 4, 26)

In [11]:
nse_companies

['360ONE.NS',
 '3MINDIA.NS',
 'ABB.NS',
 'ACC.NS',
 'AIAENG.NS',
 'APLAPOLLO.NS',
 'AUBANK.NS',
 'AARTIDRUGS.NS',
 'AARTIIND.NS',
 'AAVAS.NS',
 'ABBOTINDIA.NS',
 'ADANIENT.NS',
 'ADANIGREEN.NS',
 'ADANIPORTS.NS',
 'ADANIPOWER.NS',
 'ATGL.NS',
 'ADANITRANS.NS',
 'AWL.NS',
 'ABCAPITAL.NS',
 'ABFRL.NS',
 'AEGISCHEM.NS',
 'AETHER.NS',
 'AFFLE.NS',
 'AJANTPHARM.NS',
 'APLLTD.NS',
 'ALKEM.NS',
 'ALKYLAMINE.NS',
 'AMARAJABAT.NS',
 'AMBER.NS',
 'AMBUJACEM.NS',
 'ANGELONE.NS',
 'ANURAS.NS',
 'APARINDS.NS',
 'APOLLOHOSP.NS',
 'APOLLOTYRE.NS',
 'APTUS.NS',
 'ASAHIINDIA.NS',
 'ASHOKLEY.NS',
 'ASIANPAINT.NS',
 'ASTERDM.NS',
 'ASTRAL.NS',
 'ATUL.NS',
 'AUROPHARMA.NS',
 'AVANTIFEED.NS',
 'DMART.NS',
 'AXISBANK.NS',
 'BASF.NS',
 'BEML.NS',
 'BLS.NS',
 'BSE.NS',
 'BAJAJ-AUTO.NS',
 'BAJAJELEC.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BAJAJHLDNG.NS',
 'BALAMINES.NS',
 'BALKRISIND.NS',
 'BALRAMCHIN.NS',
 'BANDHANBNK.NS',
 'BANKBARODA.NS',
 'BANKINDIA.NS',
 'MAHABANK.NS',
 'BATAINDIA.NS',
 'BAYERCROP.NS',
 'BERGEPAINT.NS',
 'BDL.NS',
 'BEL.NS',
 'BHARATFORG.NS',
 'BHEL.NS',
 'BPCL.NS',
 'BHARTIARTL.NS',
 'BIOCON.NS',
 'BIRLACORPN.NS',
 'BSOFT.NS',
 'BLUEDART.NS',
 'BLUESTARCO.NS',
 'BBTC.NS',
 'BORORENEW.NS',
 'BOSCHLTD.NS',
 'BRIGADE.NS',
 'BCG.NS',
 'BRITANNIA.NS',
 'MAPMYINDIA.NS',
 'CCL.NS',
 'CESC.NS',
 'CGPOWER.NS',
 'CRISIL.NS',
 'CSBBANK.NS',
 'CAMPUS.NS',
 'CANFINHOME.NS',
 'CANBK.NS',
 'CGCL.NS',
 'CARBORUNIV.NS',
 'CASTROLIND.NS',
 'CEATLTD.NS',
 'CENTRALBK.NS',
 'CDSL.NS',
 'CENTURYPLY.NS',
 'CENTURYTEX.NS',
 'CERA.NS',
 'CHALET.NS',
 'CHAMBLFERT.NS',
 'CHEMPLASTS.NS',
 'CHOLAHLDNG.NS',
 'CHOLAFIN.NS',
 'CIPLA.NS',
 'CUB.NS',
 'CLEAN.NS',
 'COALINDIA.NS',
 'COCHINSHIP.NS',
 'COFORGE.NS',
 'COLPAL.NS',
 'CAMS.NS',
 'CONCOR.NS',
 'COROMANDEL.NS',
 'CRAFTSMAN.NS',
 'CREDITACC.NS',
 'CROMPTON.NS',
 'CUMMINSIND.NS',
 'CYIENT.NS',
 'DCMSHRIRAM.NS',
 'DLF.NS',
 'DABUR.NS',
 'DALBHARAT.NS',
 'DATAPATTNS.NS',
 'DEEPAKFERT.NS',
 'DEEPAKNTR.NS',
 'DELHIVERY.NS',
 'DELTACORP.NS',
 'DEVYANI.NS',
 'DIVISLAB.NS',
 'DIXON.NS',
 'LALPATHLAB.NS',
 'DRREDDY.NS',
 'EIDPARRY.NS',
 'EIHOTEL.NS',
 'EPL.NS',
 'EASEMYTRIP.NS',
 'EDELWEISS.NS',
 'EICHERMOT.NS',
 'ELGIEQUIP.NS',
 'EMAMILTD.NS',
 'ENDURANCE.NS',
 'ENGINERSIN.NS',
 'EQUITASBNK.NS',
 'ESCORTS.NS',
 'EXIDEIND.NS',
 'FDC.NS',
 'NYKAA.NS',
 'FEDERALBNK.NS',
 'FACT.NS',
 'FINEORG.NS',
 'FINCABLES.NS',
 'FINPIPE.NS',
 'FSL.NS',
 'FORTIS.NS',
 'GRINFRA.NS',
 'GAIL.NS',
 'GMMPFAUDLR.NS',
 'GMRINFRA.NS',
 'GALAXYSURF.NS',
 'GARFIBRES.NS',
 'GICRE.NS',
 'GLAND.NS',
 'GLAXO.NS',
 'GLENMARK.NS',
 'GOCOLORS.NS',
 'GODFRYPHLP.NS',
 'GODREJAGRO.NS',
 'GODREJCP.NS',
 'GODREJIND.NS',
 'GODREJPROP.NS',
 'GRANULES.NS',
 'GRAPHITE.NS',
 'GRASIM.NS',
 'GESHIP.NS',
 'GREENPANEL.NS',
 'GRINDWELL.NS',
 'GUJALKALI.NS',
 'GAEL.NS',
 'FLUOROCHEM.NS',
 'GUJGASLTD.NS',
 'GNFC.NS',
 'GPPL.NS',
 'GSFC.NS',
 'GSPL.NS',
 'HEG.NS',
 'HCLTECH.NS',
 'HDFCAMC.NS',
 'HDFCBANK.NS',
 'HDFCLIFE.NS',
 'HFCL.NS',
 'HLEGLAS.NS',
 'HAPPSTMNDS.NS',
 'HAVELLS.NS',
 'HEROMOTOCO.NS',
 'HIKAL.NS',
 'HINDALCO.NS',
 'HGS.NS',
 'HAL.NS',
 'HINDCOPPER.NS',
 'HINDPETRO.NS',
 'HINDUNILVR.NS',
 'HINDZINC.NS',
 'POWERINDIA.NS',
 'HOMEFIRST.NS',
 'HONAUT.NS',
 'HUDCO.NS',
 'HDFC.NS',
 'ICICIBANK.NS',
 'ICICIGI.NS',
 'ICICIPRULI.NS',
 'ISEC.NS',
 'IDBI.NS',
 'IDFCFIRSTB.NS',
 'IDFC.NS',
 'IFBIND.NS',
 'IIFL.NS',
 'IRB.NS',
 'ITC.NS',
 'ITI.NS',
 'INDIACEM.NS',
 'IBULHSGFIN.NS',
 'IBREALEST.NS',
 'INDIAMART.NS',
 'INDIANB.NS',
 'IEX.NS',
 'INDHOTEL.NS',
 'IOC.NS',
 'IOB.NS',
 'IRCTC.NS',
 'IRFC.NS',
 'INDIGOPNTS.NS',
 'IGL.NS',
 'INDUSTOWER.NS',
 'INDUSINDBK.NS',
 'INFIBEAM.NS',
 'NAUKRI.NS',
 'INFY.NS',
 'INGERRAND.NS',
 'INTELLECT.NS',
 'INDIGO.NS',
 'IPCALAB.NS',
 'JBCHEPHARM.NS',
 'JKCEMENT.NS',
 'JBMA.NS',
 'JKLAKSHMI.NS',
 'JKPAPER.NS',
 'JMFINANCIL.NS',
 'JSWENERGY.NS',
 'JSWSTEEL.NS',
 'JAMNAAUTO.NS',
 'JSL.NS',
 'JINDALSTEL.NS',
 'JINDWORLD.NS',
 'JUBLFOOD.NS',
 'JUBLINGREA.NS',
 'JUBLPHARMA.NS',
 'JUSTDIAL.NS',
 'JYOTHYLAB.NS',
 'KPRMILL.NS',
 'KEI.NS',
 'KNRCON.NS',
 'KPITTECH.NS',
 'KRBL.NS',
 'KSB.NS',
 'KAJARIACER.NS',
 'KALPATPOWR.NS',
 'KALYANKJIL.NS',
 'KANSAINER.NS',
 'KARURVYSYA.NS',
 'KEC.NS',
 'KENNAMET.NS',
 'KOTAKBANK.NS',
 'KIMS.NS',
 'L&TFH.NS',
 'LTTS.NS',
 'LICHSGFIN.NS',
 'LTIM.NS',
 'LAXMIMACH.NS',
 'LT.NS',
 'LATENTVIEW.NS',
 'LAURUSLABS.NS',
 'LXCHEM.NS',
 'LEMONTREE.NS',
 'LICI.NS',
 'LINDEINDIA.NS',
 'LUPIN.NS',
 'LUXIND.NS',
 'MMTC.NS',
 'MRF.NS',
 'MTARTECH.NS',
 'LODHA.NS',
 'MGL.NS',
 'M&MFIN.NS',
 'M&M.NS',
 'MAHINDCIE.NS',
 'MHRIL.NS',
 'MAHLIFE.NS',
 'MAHLOG.NS',
 'MANAPPURAM.NS',
 'MRPL.NS',
 'MARICO.NS',
 'MARUTI.NS',
 'MASTEK.NS',
 'MFSL.NS',
 'MAXHEALTH.NS',
 'MAZDOCK.NS',
 'MEDPLUS.NS',
 'MFL.NS',
 'METROBRAND.NS',
 'METROPOLIS.NS',
 'MSUMI.NS',
 'MOTILALOFS.NS',
 'MPHASIS.NS',
 'MCX.NS',
 'MUTHOOTFIN.NS',
 'NATCOPHARM.NS',
 'NBCC.NS',
 'NCC.NS',
 'NHPC.NS',
 'NLCINDIA.NS',
 'NMDC.NS',
 'NOCIL.NS',
 'NTPC.NS',
 'NH.NS',
 'NATIONALUM.NS',
 'NAVINFLUOR.NS',
 'NAZARA.NS',
 'NESTLEIND.NS',
 'NETWORK18.NS',
 'NAM-INDIA.NS',
 'NUVOCO.NS',
 'OBEROIRLTY.NS',
 'ONGC.NS',
 'OIL.NS',
 'OLECTRA.NS',
 'PAYTM.NS',
 'OFSS.NS',
 'ORIENTELEC.NS',
 'POLICYBZR.NS',
 'PCBL.NS',
 'PIIND.NS',
 'PNBHOUSING.NS',
 'PNCINFRA.NS',
 'PVR.NS',
 'PAGEIND.NS',
 'PATANJALI.NS',
 'PERSISTENT.NS',
 'PETRONET.NS',
 'PFIZER.NS',
 'PHOENIXLTD.NS',
 'PIDILITIND.NS',
 'PEL.NS',
 'POLYMED.NS',
 'POLYCAB.NS',
 'POLYPLEX.NS',
 'POONAWALLA.NS',
 'PFC.NS',
 'POWERGRID.NS',
 'PRAJIND.NS',
 'PRESTIGE.NS',
 'PRINCEPIPE.NS',
 'PRSMJOHNSN.NS',
 'PGHH.NS',
 'PNB.NS',
 'QUESS.NS',
 'RBLBANK.NS',
 'RECLTD.NS',
 'RHIM.NS',
 'RITES.NS',
 'RADICO.NS',
 'RVNL.NS',
 'RAIN.NS',
 'RAINBOW.NS',
 'RAJESHEXPO.NS',
 'RALLIS.NS',
 'RCF.NS',
 'RATNAMANI.NS',
 'RTNINDIA.NS',
 'RAYMOND.NS',
 'REDINGTON.NS',
 'RELAXO.NS',
 'RELIANCE.NS',
 'RBA.NS',
 'ROSSARI.NS',
 'ROUTE.NS',
 'SBICARD.NS',
 'SBILIFE.NS',
 'SJVN.NS',
 'SKFINDIA.NS',
 'SRF.NS',
 'MOTHERSON.NS',
 'SANOFI.NS',
 'SAPPHIRE.NS',
 'SCHAEFFLER.NS',
 'SHARDACROP.NS',
 'SHOPERSTOP.NS',
 'SHREECEM.NS',
 'RENUKA.NS',
 'SHRIRAMFIN.NS',
 'SHYAMMETL.NS',
 'SIEMENS.NS',
 'SOBHA.NS',
 'SOLARINDS.NS',
 'SONACOMS.NS',
 'SONATSOFTW.NS',
 'STARHEALTH.NS',
 'SBIN.NS',
 'SAIL.NS',
 'SWSOLAR.NS',
 'STLTECH.NS',
 'SUMICHEM.NS',
 'SPARC.NS',
 'SUNPHARMA.NS',
 'SUNTV.NS',
 'SUNDARMFIN.NS',
 'SUNDRMFAST.NS',
 'SUNTECK.NS',
 'SUPRAJIT.NS',
 'SUPREMEIND.NS',
 'SUVENPHAR.NS',
 'SUZLON.NS',
 'SWANENERGY.NS',
 'SYNGENE.NS',
 'TCIEXP.NS',
 'TCNSBRANDS.NS',
 'TTKPRESTIG.NS',
 'TV18BRDCST.NS',
 'TVSMOTOR.NS',
 'TANLA.NS',
 'TATACHEM.NS',
 'TATACOMM.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TATAELXSI.NS',
 'TATAINVEST.NS',
 'TATAMTRDVR.NS',
 'TATAMOTORS.NS',
 'TATAPOWER.NS',
 'TATASTEEL.NS',
 'TTML.NS',
 'TEAMLEASE.NS',
 'TECHM.NS',
 'TEJASNET.NS',
 'NIACL.NS',
 'RAMCOCEM.NS',
 'THERMAX.NS',
 'TIMKEN.NS',
 'TITAN.NS',
 'TORNTPHARM.NS',
 'TORNTPOWER.NS',
 'TCI.NS',
 'TRENT.NS',
 'TRIDENT.NS',
 'TRIVENI.NS',
 'TRITURBINE.NS',
 'TIINDIA.NS',
 'UCOBANK.NS',
 'UFLEX.NS',
 'UNOMINDA.NS',
 'UPL.NS',
 'UTIAMC.NS',
 'ULTRACEMCO.NS',
 'UNIONBANK.NS',
 'UBL.NS',
 'MCDOWELL-N.NS',
 'VGUARD.NS',
 'VMART.NS',
 'VIPIND.NS',
 'VAIBHAVGBL.NS',
 'VTL.NS',
 'VARROC.NS',
 'VBL.NS',
 'MANYAVAR.NS',
 'VEDL.NS',
 'VIJAYA.NS',
 'VINATIORGA.NS',
 'IDEA.NS',
 'VOLTAS.NS',
 'WELCORP.NS',
 'WELSPUNIND.NS',
 'WESTLIFE.NS',
 'WHIRLPOOL.NS',
 'WIPRO.NS',
 'YESBANK.NS',
 'ZFCVINDIA.NS',
 'ZEEL.NS',
 'ZENSARTECH.NS',
 'ZOMATO.NS',
 'ZYDUSLIFE.NS',
 'ZYDUSWELL.NS',
 'ECLERX.NS']

In [12]:
len(nse_companies)

493

In [13]:
days_shape = 60

In [14]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

In [15]:


model11 = load_model('model_filtered_data02.h5')
    #model12 = joblib.load('model12.pkl')
    #model13 = joblib.load('model13.pkl')
    #model21 = joblib.load('model21.pkl')
    #model22 = joblib.load('model22.pkl')
    #model23 = joblib.load('model23.pkl')    
    #model31 = joblib.load('model31.pkl')
    #model32 = joblib.load('model32.pkl')
    #model33 = joblib.load('model33.pkl')

In [16]:
y_all =[]
count = 0 
for company in nse_companies:
    
    print('Completed',count,'out of',len(nse_companies),'steps')
    count = count+1
    
    current_data = data[company]
    current_data = current_data.iloc[::-1]  #reversing rows to get current date first
    
    current_data['Date'] = current_data.index
    current_data = current_data.reset_index(drop=True)
    current_data = current_data[['Date','Close']]
    print('the main data is of shape',current_data.shape) 
    
    current_data_05 = current_data
    current_data_05['Xth'] = current_data['Close']
    
    c1 = []
    for i in range(1,days_shape):
        current_data_05['temp'] = current_data_05.loc[:,'Xth'] - current_data_05.loc[:,'Xth'].shift(-1*i)
        current_data_05['temp'] = current_data_05.loc[:,'temp']/current_data_05.loc[:,'Xth']*100
        c1.append(current_data_05['temp'].to_numpy())
    #print('the lenth of concatenated stuff is',len(c1[0]))
    
    current_data1 = pd.DataFrame(c1)
    current_data2 = current_data1.transpose()    
    print('shape of current_data2 is',current_data2.shape )   

    
    c2 =current_data2.to_numpy()
    
    c3 =[]

    for i in range(int(len(c2)-days_shape)):
        c6 = np.concatenate((c2[i:i+days_shape]))
        c3.append(c6)

    aes = current_data.shape[0]
    
    df4 = pd.DataFrame(c3)
    df4['Xth'] = current_data_05.iloc[:aes]['Xth']
    
     
    df5 = df4.dropna()
    
    df6 = df5
    

 ####################################################           
            
    df7 = df6.drop('Xth',axis=1)     

    
    X1 = df7

    import numpy as np
     
        
    X_1 = np.asarray(X1).astype(np.float32)

    print('shape of X_1 is',X_1.shape)

    yp11 = model11.predict(X_1)
    #yp12 = model12.predict(X_1)
    #yp13 = model13.predict(X_1)
    #yp21 = model21.predict(X_1)
    #yp22 = model22.predict(X_1)
    #yp23 = model23.predict(X_1)
    #yp31 = model31.predict(X_1)
    #yp32 = model32.predict(X_1)
    #yp33 = model33.predict(X_1)
    
    #y_single =[]
    #y_single.append(yp11[0])
    #y_single.append(yp12[0])
    #y_single.append(yp13[0])
    #y_single.append(yp21[0])
    #y_single.append(yp22[0])
    #y_single.append(yp23[0])
    #y_single.append(yp31[0])
    #y_single.append(yp32[0])
    #y_single.append(yp33[0])     
    
    y_all.append(yp11[0])

Completed 0 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 3s 6ms/step
Completed 1 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 2 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 3 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 4 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 5 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 6 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 7 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 8 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 9 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 10 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 11 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 12 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 6ms/step
Completed 13 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 14 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 15 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 16 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 17 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 18 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 19 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 20 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 21 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 6ms/step
Completed 22 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 23 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 6ms/step
Completed 24 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 25 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 26 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 27 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 28 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 5ms/step
Completed 29 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 30 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 31 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 32 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 33 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 34 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 35 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 36 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 37 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 38 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 39 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 40 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 11ms/step
Completed 41 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 42 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 43 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 44 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 45 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 46 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 47 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 48 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 49 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 50 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 51 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 52 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 53 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 54 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 55 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 56 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 57 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 58 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 59 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 60 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 61 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 62 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 63 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 64 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 65 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 66 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 67 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 68 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 69 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 70 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 71 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 72 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)
1/3 [=========>....................] - ETA: 0s

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 73 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 74 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 75 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 76 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 77 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 78 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 79 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 80 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 81 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 82 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 83 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 84 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 85 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 86 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 87 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 88 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 89 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 90 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 91 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 92 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 93 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 94 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 95 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 96 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 97 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 98 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 99 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 4ms/step
Completed 100 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 8ms/step
Completed 101 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 102 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 103 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 104 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 105 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 106 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 107 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 108 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 109 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 110 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 111 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 112 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 113 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 114 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 115 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 116 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 117 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 118 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 4ms/step
Completed 119 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 120 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 121 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 122 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 123 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 124 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 125 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 126 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 127 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 128 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 129 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 130 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 131 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 132 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 133 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 134 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 135 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 136 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 137 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 138 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 139 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 140 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 141 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 142 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 143 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 144 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 145 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 146 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 147 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 148 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 149 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 150 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 151 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 8ms/step
Completed 152 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 153 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 154 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 155 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 156 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 157 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 158 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 159 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 160 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 161 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 162 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 163 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 164 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 165 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 166 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 167 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 168 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 169 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 170 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 171 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 172 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 173 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 174 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 175 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 176 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 177 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 178 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 179 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 180 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 181 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 182 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 183 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 184 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 7ms/step
Completed 185 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 186 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 187 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 188 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 189 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 190 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 191 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 192 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 193 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 194 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 195 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 196 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 197 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 198 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 199 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 200 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 201 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 202 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 203 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 204 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 205 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 206 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 207 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 208 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 209 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 210 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 211 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 212 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 213 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 214 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 215 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 216 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 217 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 218 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 219 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 220 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 221 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 222 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 223 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 224 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 3ms/step
Completed 225 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)
shape of X_1 is (77, 3540)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

3/3 [==============================] - 0s 6ms/step
Completed 226 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 227 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 228 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 229 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 230 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 231 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 232 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 233 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 234 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 235 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 236 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 237 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 238 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 239 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 240 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 241 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 242 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 243 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 244 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 245 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 246 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 247 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 248 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 249 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 250 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 251 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 252 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 253 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 254 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 255 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 256 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 257 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 258 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 259 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 260 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 261 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 262 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 263 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 264 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 265 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 266 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 267 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 268 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 14ms/step
Completed 269 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 270 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 271 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 272 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 273 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 274 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 275 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 276 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 277 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 278 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 279 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 280 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 281 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 282 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 283 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 284 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 285 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 286 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 287 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 288 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 289 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 290 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 291 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 292 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 293 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 294 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 295 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 296 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 297 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 298 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 299 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 300 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 301 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 302 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 303 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 304 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 305 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 306 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 307 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 308 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 309 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 310 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 311 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 312 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 313 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 314 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 315 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 316 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 317 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 318 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 319 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 320 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 321 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 322 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 323 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 324 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 325 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 326 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 327 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 328 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 329 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 330 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 331 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 332 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 333 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 334 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 335 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 336 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 337 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 338 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 339 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 340 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 341 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 342 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 343 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 344 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 345 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 346 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 347 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 348 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 349 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 350 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 351 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 352 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 353 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 354 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 355 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 356 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 357 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 358 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 359 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 360 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 361 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 362 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 363 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 364 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 365 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 366 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 367 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 368 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 369 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 370 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 371 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 372 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 373 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 374 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 375 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 376 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 377 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 378 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 379 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 380 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 381 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 382 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 383 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 384 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 385 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 386 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 387 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 388 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 389 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 390 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 391 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 392 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 393 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 394 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 395 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 396 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 397 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 398 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 399 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 400 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 401 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 402 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 403 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 404 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 405 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 406 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 407 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 16ms/step
Completed 408 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 409 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 410 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 411 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 412 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 413 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 414 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 415 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 416 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 417 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 418 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 419 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 420 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 421 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 422 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 423 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 20ms/step
Completed 424 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 425 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 426 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 427 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 428 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 429 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 430 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 431 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 432 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 433 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 434 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 435 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 436 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 437 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 438 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 3ms/step
Completed 439 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 440 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 441 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 442 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 443 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 444 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 445 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 446 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 447 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 448 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 449 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 11ms/step
Completed 450 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 451 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 452 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 453 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 454 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 455 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 456 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 457 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 458 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 459 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 460 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 461 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 462 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 13ms/step
Completed 463 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 464 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 465 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 466 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 467 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 5ms/step
Completed 468 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 469 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 470 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 471 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 472 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 473 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 474 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 475 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 476 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 477 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 478 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 479 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 480 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 481 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 482 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step
Completed 483 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 484 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 4ms/step
Completed 485 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 7ms/step
Completed 486 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 10ms/step
Completed 487 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 488 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 489 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 9ms/step
Completed 490 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 8ms/step
Completed 491 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 6ms/step
Completed 492 out of 493 steps
the main data is of shape (195, 2)
shape of current_data2 is (195, 59)

C:\Users\abhij\AppData\Local\Temp\ipykernel_27628\1005566513.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_data['Date'] = current_data.index

shape of X_1 is (77, 3540)
3/3 [==============================] - 0s 12ms/step

In [17]:
print(len(X_1[0]))

3540

In [18]:
nse_companies[36]

'ASAHIINDIA.NS'

In [19]:
data[nse_companies[36]]

                  Open        High         Low       Close   Adj Close  Volume
Date
2022-07-11  573.799988  578.849976  561.150024  566.250000  562.849792  258334
2022-07-12  564.849976  575.549988  559.200012  563.500000  560.116333  122273
2022-07-13  566.000000  581.950012  561.900024  566.349976  562.949158  192078
2022-07-14  567.750000  576.400024  546.500000  550.750000  547.442871  194434
2022-07-15  554.500000  574.000000  552.500000  568.700012  565.285095  235200
...                ...         ...         ...         ...         ...     ...
2023-04-19  460.950012  474.950012  460.950012  472.700012  472.700012   86565
2023-04-20  473.000000  477.700012  462.500000  463.200012  463.200012   94289
2023-04-21  463.000000  465.549988  458.399994  460.899994  460.899994   45153
2023-04-24  462.950012  463.950012  453.799988  454.450012  454.450012   73839
2023-04-25  454.000000  457.000000  446.850006  448.750000  448.750000   84240

[195 rows x 6 columns]

In [20]:
y_all

[array([0.00310215], dtype=float32),
 array([0.00039138], dtype=float32),
 array([8.822319e-06], dtype=float32),
 array([0.00375366], dtype=float32),
 array([0.08587109], dtype=float32),
 array([0.00018969], dtype=float32),
 array([0.00112995], dtype=float32),
 array([0.00034815], dtype=float32),
 array([0.00335674], dtype=float32),
 array([0.00037491], dtype=float32),
 array([0.00224627], dtype=float32),
 array([1.384067e-05], dtype=float32),
 array([4.4924353e-05], dtype=float32),
 array([0.00042731], dtype=float32),
 array([1.43359175e-05], dtype=float32),
 array([3.1189953e-10], dtype=float32),
 array([0.00014774], dtype=float32),
 array([0.00237651], dtype=float32),
 array([0.00308878], dtype=float32),
 array([0.00493014], dtype=float32),
 array([0.00198118], dtype=float32),
 array([0.00345824], dtype=float32),
 array([0.00068128], dtype=float32),
 array([0.0034648], dtype=float32),
 array([0.00226059], dtype=float32),
 array([0.00071497], dtype=float32),
 array([0.00377279], dtype=float32),
 array([0.00383168], dtype=float32),
 array([0.00114881], dtype=float32),
 array([0.00162803], dtype=float32),
 array([0.00326959], dtype=float32),
 array([8.160955e-05], dtype=float32),
 array([0.0012349], dtype=float32),
 array([0.00138461], dtype=float32),
 array([0.0036555], dtype=float32),
 array([0.00393119], dtype=float32),
 array([0.00323797], dtype=float32),
 array([0.0021223], dtype=float32),
 array([0.00229947], dtype=float32),
 array([0.00240213], dtype=float32),
 array([0.00546377], dtype=float32),
 array([0.00032613], dtype=float32),
 array([0.00172891], dtype=float32),
 array([0.00345259], dtype=float32),
 array([0.00138464], dtype=float32),
 array([0.00419168], dtype=float32),
 array([0.00393953], dtype=float32),
 array([0.00174972], dtype=float32),
 array([0.00195898], dtype=float32),
 array([0.00282685], dtype=float32),
 array([0.0027757], dtype=float32),
 array([0.00255256], dtype=float32),
 array([0.00262991], dtype=float32),
 array([0.00323091], dtype=float32),
 array([0.00228884], dtype=float32),
 array([0.00262759], dtype=float32),
 array([0.00394597], dtype=float32),
 array([0.00314603], dtype=float32),
 array([0.00086662], dtype=float32),
 array([0.00447411], dtype=float32),
 array([0.00588547], dtype=float32),
 array([0.00080717], dtype=float32),
 array([0.00410358], dtype=float32),
 array([0.00214207], dtype=float32),
 array([8.893113e-05], dtype=float32),
 array([0.00253019], dtype=float32),
 array([0.00389276], dtype=float32),
 array([0.00354749], dtype=float32),
 array([0.00332635], dtype=float32),
 array([0.00211325], dtype=float32),
 array([0.00247679], dtype=float32),
 array([0.0018045], dtype=float32),
 array([0.00269424], dtype=float32),
 array([0.00305952], dtype=float32),
 array([0.00147216], dtype=float32),
 array([0.00012401], dtype=float32),
 array([0.00066217], dtype=float32),
 array([8.002647e-05], dtype=float32),
 array([6.2075414e-05], dtype=float32),
 array([0.00268266], dtype=float32),
 array([1.], dtype=float32),
 array([0.00152784], dtype=float32),
 array([0.00047765], dtype=float32),
 array([5.5045707e-06], dtype=float32),
 array([0.00336797], dtype=float32),
 array([0.00064213], dtype=float32),
 array([0.00020155], dtype=float32),
 array([0.00214301], dtype=float32),
 array([0.00265463], dtype=float32),
 array([0.00192669], dtype=float32),
 array([0.00414015], dtype=float32),
 array([0.00326489], dtype=float32),
 array([0.00267172], dtype=float32),
 array([0.00425932], dtype=float32),
 array([0.00208541], dtype=float32),
 array([0.00373046], dtype=float32),
 array([0.00259169], dtype=float32),
 array([0.00189215], dtype=float32),
 array([0.00452652], dtype=float32),
 array([0.00019941], dtype=float32),
 array([0.00102569], dtype=float32),
 array([0.00529529], dtype=float32),
 array([9.8818586e-05], dtype=float32),
 array([0.00300855], dtype=float32),
 array([0.00265038], dtype=float32),
 array([0.00140718], dtype=float32),
 array([0.00331093], dtype=float32),
 array([0.00316057], dtype=float32),
 array([0.00294856], dtype=float32),
 array([0.00253782], dtype=float32),
 array([0.00163428], dtype=float32),
 array([0.00240816], dtype=float32),
 array([8.320782e-06], dtype=float32),
 array([0.00404589], dtype=float32),
 array([0.00314247], dtype=float32),
 array([0.00137341], dtype=float32),
 array([0.00135332], dtype=float32),
 array([0.9953479], dtype=float32),
 array([0.00047516], dtype=float32),
 array([0.00174338], dtype=float32),
 array([0.00294042], dtype=float32),
 array([0.00164136], dtype=float32),
 array([0.00070042], dtype=float32),
 array([0.0012542], dtype=float32),
 array([0.00023765], dtype=float32),
 array([0.00269046], dtype=float32),
 array([0.00274121], dtype=float32),
 array([0.00223423], dtype=float32),
 array([0.0033112], dtype=float32),
 array([0.00162272], dtype=float32),
 array([0.00096542], dtype=float32),
 array([0.00210274], dtype=float32),
 array([0.00345068], dtype=float32),
 array([0.00295509], dtype=float32),
 array([0.0030565], dtype=float32),
 array([0.00467334], dtype=float32),
 array([0.00144261], dtype=float32),
 array([0.00286473], dtype=float32),
 array([0.00260623], dtype=float32),
 array([0.0021986], dtype=float32),
 array([0.00055832], dtype=float32),
 array([0.00276151], dtype=float32),
 array([0.00377223], dtype=float32),
 array([0.00188832], dtype=float32),
 array([4.807329e-06], dtype=float32),
 array([0.00370439], dtype=float32),
 array([0.00425368], dtype=float32),
 array([0.00214003], dtype=float32),
 array([0.10625566], dtype=float32),
 array([0.00441601], dtype=float32),
 array([4.543664e-21], dtype=float32),
 array([0.00449236], dtype=float32),
 array([4.3783044e-07], dtype=float32),
 array([0.00642612], dtype=float32),
 array([0.0016331], dtype=float32),
 array([0.0031129], dtype=float32),
 array([0.00096062], dtype=float32),
 array([0.00102518], dtype=float32),
 array([0.00232114], dtype=float32),
 array([0.00276722], dtype=float32),
 array([0.00307446], dtype=float32),
 array([0.00312016], dtype=float32),
 array([0.00096888], dtype=float32),
 array([0.00260889], dtype=float32),
 array([0.00028924], dtype=float32),
 array([0.00245402], dtype=float32),
 array([0.00418727], dtype=float32),
 array([0.00678723], dtype=float32),
 array([0.00458491], dtype=float32),
 array([0.00189649], dtype=float32),
 array([0.00461529], dtype=float32),
 array([5.1188876e-05], dtype=float32),
 array([0.00407706], dtype=float32),
 array([0.00324008], dtype=float32),
 array([0.00262936], dtype=float32),
 array([0.00276321], dtype=float32),
 array([0.00125067], dtype=float32),
 array([0.00214191], dtype=float32),
 array([0.00427067], dtype=float32),
 array([0.00151535], dtype=float32),
 array([0.0008437], dtype=float32),
 array([0.00027496], dtype=float32),
 array([0.00332598], dtype=float32),
 array([5.400714e-06], dtype=float32),
 array([0.00455882], dtype=float32),
 array([5.780833e-05], dtype=float32),
 array([0.0013627], dtype=float32),
 array([0.00028121], dtype=float32),
 array([0.00472212], dtype=float32),
 array([0.00366079], dtype=float32),
 array([0.00409496], dtype=float32),
 array([0.00485095], dtype=float32),
 array([3.7092745e-05], dtype=float32),
 array([0.00256241], dtype=float32),
 array([0.00172216], dtype=float32),
 array([0.00398779], dtype=float32),
 array([0.00614223], dtype=float32),
 array([0.0033496], dtype=float32),
 array([0.00289306], dtype=float32),
 array([0.00056048], dtype=float32),
 array([0.00440026], dtype=float32),
 array([0.0033849], dtype=float32),
 array([0.00074674], dtype=float32),
 array([0.00286542], dtype=float32),
 array([0.00051903], dtype=float32),
 array([0.00255086], dtype=float32),
 array([0.00131582], dtype=float32),
 array([0.00309269], dtype=float32),
 array([0.00414616], dtype=float32),
 array([0.00430196], dtype=float32),
 array([0.00058282], dtype=float32),
 array([0.00366305], dtype=float32),
 array([0.00369552], dtype=float32),
 array([0.0009101], dtype=float32),
 array([0.00473277], dtype=float32),
 array([0.0043243], dtype=float32),
 array([0.00043755], dtype=float32),
 array([0.00276903], dtype=float32),
 array([0.00186135], dtype=float32),
 array([0.00090491], dtype=float32),
 array([0.00456874], dtype=float32),
 array([0.00275346], dtype=float32),
 array([0.00421429], dtype=float32),
 array([3.08802e-07], dtype=float32),
 array([0.00182317], dtype=float32),
 array([0.0029511], dtype=float32),
 array([0.00052757], dtype=float32),
 array([0.00354924], dtype=float32),
 array([0.00239522], dtype=float32),
 array([0.00547809], dtype=float32),
 array([0.00366801], dtype=float32),
 array([0.00179902], dtype=float32),
 array([0.00216923], dtype=float32),
 array([0.00213875], dtype=float32),
 array([0.00128262], dtype=float32),
 array([0.00506137], dtype=float32),
 array([0.00201314], dtype=float32),
 array([0.00236363], dtype=float32),
 array([0.9999665], dtype=float32),
 array([0.00126254], dtype=float32),
 array([0.00132949], dtype=float32),
 array([0.0043697], dtype=float32),
 array([0.00100516], dtype=float32),
 array([0.00387237], dtype=float32),
 array([0.00051459], dtype=float32),
 array([0.00015824], dtype=float32),
 array([0.00323576], dtype=float32),
 array([0.00042329], dtype=float32),
 array([0.00461365], dtype=float32),
 array([0.00143708], dtype=float32),
 array([0.00437365], dtype=float32),
 array([0.00430823], dtype=float32),
 array([0.00242374], dtype=float32),
 array([0.00328765], dtype=float32),
 array([0.00109474], dtype=float32),
 array([0.00384323], dtype=float32),
 array([0.00220207], dtype=float32),
 array([0.00398125], dtype=float32),
 array([0.00197469], dtype=float32),
 array([0.00301122], dtype=float32),
 array([9.525274e-05], dtype=float32),
 array([0.0008082], dtype=float32),
 array([0.0015196], dtype=float32),
 array([0.00036511], dtype=float32),
 array([0.00328281], dtype=float32),
 array([0.00207531], dtype=float32),
 array([0.00284426], dtype=float32),
 array([0.00134163], dtype=float32),
 array([0.0090689], dtype=float32),
 array([5.5118517e-06], dtype=float32),
 array([0.01587465], dtype=float32),
 array([0.00133588], dtype=float32),
 array([0.0030575], dtype=float32),
 array([0.00322237], dtype=float32),
 array([0.00178918], dtype=float32),
 array([0.00267591], dtype=float32),
 array([0.00029255], dtype=float32),
 array([0.00445467], dtype=float32),
 array([0.9739623], dtype=float32),
 array([0.00447614], dtype=float32),
 array([0.0019842], dtype=float32),
 array([0.00226314], dtype=float32),
 array([0.00342751], dtype=float32),
 array([0.0002117], dtype=float32),
 array([0.00205162], dtype=float32),
 array([0.00493354], dtype=float32),
 array([2.3346412e-05], dtype=float32),
 array([0.00347093], dtype=float32),
 array([0.00083529], dtype=float32),
 array([0.00440075], dtype=float32),
 array([0.00451799], dtype=float32),
 array([0.0018018], dtype=float32),
 array([0.00494042], dtype=float32),
 array([0.0005038], dtype=float32),
 array([0.00164553], dtype=float32),
 array([0.00282534], dtype=float32),
 array([0.00157199], dtype=float32),
 array([0.00163532], dtype=float32),
 array([0.00283471], dtype=float32),
 array([0.00367106], dtype=float32),
 array([0.0036078], dtype=float32),
 array([0.00325576], dtype=float32),
 array([4.2800184e-07], dtype=float32),
 array([0.00229513], dtype=float32),
 array([0.00113306], dtype=float32),
 array([0.00190987], dtype=float32),
 array([0.00139606], dtype=float32),
 array([0.00117303], dtype=float32),
 array([0.00191597], dtype=float32),
 array([0.00146159], dtype=float32),
 array([0.00261827], dtype=float32),
 array([0.00209026], dtype=float32),
 array([0.00442146], dtype=float32),
 array([0.00342815], dtype=float32),
 array([0.00066255], dtype=float32),
 array([0.00059956], dtype=float32),
 array([0.00445859], dtype=float32),
 array([0.00023756], dtype=float32),
 array([0.00237422], dtype=float32),
 array([0.00253412], dtype=float32),
 array([0.00356357], dtype=float32),
 array([0.0037493], dtype=float32),
 array([0.00390496], dtype=float32),
 array([0.00189094], dtype=float32),
 array([0.00030288], dtype=float32),
 array([5.1657727e-05], dtype=float32),
 array([0.00324067], dtype=float32),
 array([0.00249846], dtype=float32),
 array([0.00446737], dtype=float32),
 array([0.00408225], dtype=float32),
 array([0.00318133], dtype=float32),
 array([0.00181863], dtype=float32),
 array([0.00020135], dtype=float32),
 array([0.00294484], dtype=float32),
 array([0.00187555], dtype=float32),
 array([0.00068825], dtype=float32),
 array([0.00099677], dtype=float32),
 array([0.00034077], dtype=float32),
 array([0.00206183], dtype=float32),
 array([1.], dtype=float32),
 array([0.00042751], dtype=float32),
 array([0.00344802], dtype=float32),
 array([0.00334254], dtype=float32),
 array([0.00038243], dtype=float32),
 array([0.00139094], dtype=float32),
 array([0.00031636], dtype=float32),
 array([0.00341217], dtype=float32),
 array([0.0041612], dtype=float32),
 array([0.00056806], dtype=float32),
 array([0.00271055], dtype=float32),
 array([0.003282], dtype=float32),
 array([0.00457622], dtype=float32),
 array([0.00282529], dtype=float32),
 array([0.00399626], dtype=float32),
 array([3.6400765e-05], dtype=float32),
 array([0.00218007], dtype=float32),
 array([0.00216407], dtype=float32),
 array([0.00159533], dtype=float32),
 array([0.00290909], dtype=float32),
 array([0.00224041], dtype=float32),
 array([0.00347513], dtype=float32),
 array([0.00119213], dtype=float32),
 array([0.00309321], dtype=float32),
 array([0.00098126], dtype=float32),
 array([0.00345976], dtype=float32),
 array([0.00569051], dtype=float32),
 array([0.00283733], dtype=float32),
 array([0.00338071], dtype=float32),
 array([0.00442597], dtype=float32),
 array([0.00439106], dtype=float32),
 array([0.00237677], dtype=float32),
 array([0.00036918], dtype=float32),
 array([1.297745e-06], dtype=float32),
 array([0.00486071], dtype=float32),
 array([0.00285635], dtype=float32),
 array([0.9264678], dtype=float32),
 array([0.00448669], dtype=float32),
 array([0.00372323], dtype=float32),
 array([0.00251086], dtype=float32),
 array([0.00136624], dtype=float32),
 array([1.5556898e-08], dtype=float32),
 array([0.00332838], dtype=float32),
 array([0.00057076], dtype=float32),
 array([0.00380596], dtype=float32),
 array([0.00399394], dtype=float32),
 array([0.0016788], dtype=float32),
 array([0.0039316], dtype=float32),
 array([0.00394721], dtype=float32),
 array([0.00320326], dtype=float32),
 array([0.00400687], dtype=float32),
 array([1.825421e-05], dtype=float32),
 array([0.00177562], dtype=float32),
 array([0.00089092], dtype=float32),
 array([0.00314415], dtype=float32),
 array([0.00242654], dtype=float32),
 array([1.8514951e-05], dtype=float32),
 array([0.0186037], dtype=float32),
 array([0.00105972], dtype=float32),
 array([0.00507073], dtype=float32),
 array([0.00329313], dtype=float32),
 array([0.00291302], dtype=float32),
 array([0.00067444], dtype=float32),
 array([1.2764434e-05], dtype=float32),
 array([0.00152927], dtype=float32),
 array([0.00281625], dtype=float32),
 array([0.00116619], dtype=float32),
 array([3.277987e-06], dtype=float32),
 array([0.00167019], dtype=float32),
 array([0.00446033], dtype=float32),
 array([0.00300972], dtype=float32),
 array([9.754103e-05], dtype=float32),
 array([0.00259541], dtype=float32),
 array([0.00165949], dtype=float32),
 array([0.00305737], dtype=float32),
 array([6.4737425e-05], dtype=float32),
 array([0.00500405], dtype=float32),
 array([0.00224677], dtype=float32),
 array([0.00225586], dtype=float32),
 array([0.003807], dtype=float32),
 array([0.00020522], dtype=float32),
 array([0.00098342], dtype=float32),
 array([0.00052042], dtype=float32),
 array([0.00704108], dtype=float32),
 array([0.00501304], dtype=float32),
 array([0.00385615], dtype=float32),
 array([0.00386443], dtype=float32),
 array([0.0025456], dtype=float32),
 array([0.00295788], dtype=float32),
 array([0.00419408], dtype=float32),
 array([0.0005416], dtype=float32),
 array([0.00010523], dtype=float32),
 array([4.765692e-05], dtype=float32),
 array([0.00196577], dtype=float32),
 array([0.00052304], dtype=float32),
 array([0.00358134], dtype=float32),
 array([0.00251565], dtype=float32),
 array([0.00034162], dtype=float32),
 array([0.00056165], dtype=float32),
 array([0.00165286], dtype=float32),
 array([0.00330802], dtype=float32),
 array([0.00294053], dtype=float32),
 array([0.00122695], dtype=float32),
 array([7.381224e-05], dtype=float32),
 array([0.07992782], dtype=float32),
 array([0.00179775], dtype=float32),
 array([0.00437611], dtype=float32),
 array([0.00119781], dtype=float32),
 array([7.742945e-06], dtype=float32),
 array([0.00407065], dtype=float32),
 array([0.00224387], dtype=float32),
 array([0.00432695], dtype=float32),
 array([0.00032314], dtype=float32),
 array([0.00052857], dtype=float32),
 array([0.00020741], dtype=float32),
 array([0.00161515], dtype=float32),
 array([0.00305115], dtype=float32),
 array([1.6451982e-05], dtype=float32),
 array([0.00211446], dtype=float32),
 array([0.00350339], dtype=float32),
 array([5.3168897e-05], dtype=float32),
 array([0.00273682], dtype=float32),
 array([0.00206095], dtype=float32),
 array([0.00465621], dtype=float32),
 array([0.00088049], dtype=float32),
 array([0.00290605], dtype=float32),
 array([0.00273636], dtype=float32),
 array([0.00262544], dtype=float32),
 array([0.00426763], dtype=float32),
 array([0.00252959], dtype=float32),
 array([0.00406694], dtype=float32),
 array([0.00099894], dtype=float32),
 array([0.00271807], dtype=float32),
 array([0.00205773], dtype=float32),
 array([0.00149124], dtype=float32),
 array([0.0018317], dtype=float32),
 array([0.00206939], dtype=float32),
 array([0.98563486], dtype=float32),
 array([0.0023124], dtype=float32),
 array([0.00472745], dtype=float32),
 array([0.00028855], dtype=float32),
 array([0.00263541], dtype=float32),
 array([1.3018248e-05], dtype=float32),
 array([0.0041256], dtype=float32),
 array([0.00319633], dtype=float32),
 array([0.00221705], dtype=float32),
 array([0.00503769], dtype=float32),
 array([4.032513e-06], dtype=float32),
 array([0.9998846], dtype=float32),
 array([1.1036485e-07], dtype=float32),
 array([0.00153852], dtype=float32),
 array([0.00149732], dtype=float32),
 array([0.00018316], dtype=float32),
 array([0.00025978], dtype=float32)]

In [21]:
y_all = np.array(y_all)
y_all

array([[3.10215401e-03],
       [3.91380861e-04],
       [8.82231870e-06],
       [3.75365675e-03],
       [8.58710855e-02],
       [1.89685568e-04],
       [1.12994981e-03],
       [3.48153233e-04],
       [3.35674104e-03],
       [3.74906551e-04],
       [2.24626600e-03],
       [1.38406704e-05],
       [4.49243526e-05],
       [4.27307095e-04],
       [1.43359175e-05],
       [3.11899534e-10],
       [1.47737286e-04],
       [2.37650541e-03],
       [3.08877835e-03],
       [4.93013766e-03],
       [1.98118039e-03],
       [3.45824333e-03],
       [6.81280857e-04],
       [3.46479611e-03],
       [2.26059463e-03],
       [7.14968017e-04],
       [3.77278728e-03],
       [3.83168459e-03],
       [1.14881119e-03],
       [1.62803417e-03],
       [3.26959323e-03],
       [8.16095489e-05],
       [1.23490079e-03],
       [1.38460798e-03],
       [3.65550350e-03],
       [3.93118523e-03],
       [3.23797250e-03],
       [2.12230370e-03],
       [2.29947339e-03],
       [2.40212958e-03],
       [5.46377338e-03],
       [3.26129375e-04],
       [1.72890560e-03],
       [3.45259300e-03],
       [1.38464163e-03],
       [4.19167755e-03],
       [3.93953267e-03],
       [1.74972275e-03],
       [1.95898488e-03],
       [2.82684760e-03],
       [2.77569727e-03],
       [2.55255937e-03],
       [2.62991362e-03],
       [3.23090539e-03],
       [2.28884094e-03],
       [2.62759323e-03],
       [3.94597463e-03],
       [3.14602861e-03],
       [8.66615272e-04],
       [4.47411276e-03],
       [5.88546926e-03],
       [8.07167788e-04],
       [4.10358142e-03],
       [2.14207056e-03],
       [8.89311268e-05],
       [2.53019412e-03],
       [3.89276049e-03],
       [3.54749430e-03],
       [3.32635059e-03],
       [2.11325241e-03],
       [2.47678533e-03],
       [1.80450070e-03],
       [2.69424217e-03],
       [3.05952365e-03],
       [1.47216499e-03],
       [1.24005106e-04],
       [6.62170583e-04],
       [8.00264679e-05],
       [6.20754145e-05],
       [2.68266280e-03],
       [1.00000000e+00],
       [1.52783701e-03],
       [4.77650552e-04],
       [5.50457071e-06],
       [3.36797419e-03],
       [6.42133236e-04],
       [2.01549788e-04],
       [2.14300654e-03],
       [2.65463069e-03],
       [1.92669441e-03],
       [4.14015446e-03],
       [3.26488633e-03],
       [2.67171860e-03],
       [4.25932277e-03],
       [2.08541262e-03],
       [3.73046007e-03],
       [2.59169051e-03],
       [1.89214852e-03],
       [4.52651875e-03],
       [1.99409827e-04],
       [1.02568662e-03],
       [5.29529480e-03],
       [9.88185857e-05],
       [3.00855073e-03],
       [2.65038223e-03],
       [1.40718278e-03],
       [3.31093068e-03],
       [3.16056912e-03],
       [2.94855749e-03],
       [2.53782328e-03],
       [1.63428066e-03],
       [2.40815571e-03],
       [8.32078240e-06],
       [4.04589390e-03],
       [3.14246863e-03],
       [1.37340627e-03],
       [1.35332358e-03],
       [9.95347917e-01],
       [4.75161069e-04],
       [1.74338208e-03],
       [2.94042123e-03],
       [1.64136337e-03],
       [7.00420700e-04],
       [1.25420315e-03],
       [2.37654560e-04],
       [2.69045611e-03],
       [2.74120900e-03],
       [2.23423075e-03],
       [3.31119983e-03],
       [1.62271515e-03],
       [9.65416373e-04],
       [2.10273731e-03],
       [3.45067726e-03],
       [2.95509282e-03],
       [3.05650430e-03],
       [4.67333989e-03],
       [1.44260633e-03],
       [2.86473427e-03],
       [2.60623265e-03],
       [2.19860207e-03],
       [5.58316242e-04],
       [2.76151299e-03],
       [3.77223478e-03],
       [1.88831880e-03],
       [4.80732888e-06],
       [3.70438700e-03],
       [4.25367989e-03],
       [2.14003026e-03],
       [1.06255658e-01],
       [4.41601081e-03],
       [4.54366393e-21],
       [4.49235970e-03],
       [4.37830437e-07],
       [6.42612064e-03],
       [1.63309916e-03],
       [3.11290193e-03],
       [9.60618258e-04],
       [1.02517882e-03],
       [2.32114084e-03],
       [2.76722084e-03],
       [3.07445764e-03],
       [3.12015996e-03],
       [9.68879147e-04],
       [2.60888762e-03],
       [2.89241114e-04],
       [2.45402008e-03],
       [4.18726774e-03],
       [6.78723166e-03],
       [4.58490849e-03],
       [1.89649302e-03],
       [4.61529475e-03],
       [5.11888757e-05],
       [4.07705735e-03],
       [3.24007566e-03],
       [2.62936438e-03],
       [2.76321406e-03],
       [1.25067274e-03],
       [2.14191154e-03],
       [4.27067280e-03],
       [1.51534914e-03],
       [8.43699614e-04],
       [2.74955441e-04],
       [3.32597923e-03],
       [5.40071414e-06],
       [4.55881562e-03],
       [5.78083309e-05],
       [1.36270095e-03],
       [2.81209504e-04],
       [4.72211931e-03],
       [3.66078736e-03],
       [4.09496389e-03],
       [4.85095382e-03],
       [3.70927446e-05],
       [2.56240857e-03],
       [1.72215654e-03],
       [3.98778543e-03],
       [6.14223303e-03],
       [3.34959757e-03],
       [2.89305602e-03],
       [5.60479180e-04],
       [4.40025935e-03],
       [3.38490400e-03],
       [7.46738515e-04],
       [2.86542089e-03],
       [5.19033172e-04],
       [2.55085668e-03],
       [1.31581503e-03],
       [3.09268688e-03],
       [4.14615730e-03],
       [4.30195872e-03],
       [5.82819455e-04],
       [3.66304861e-03],
       [3.69551894e-03],
       [9.10103787e-04],
       [4.73276945e-03],
       [4.32430208e-03],
       [4.37547889e-04],
       [2.76902923e-03],
       [1.86135073e-03],
       [9.04913119e-04],
       [4.56873700e-03],
       [2.75345822e-03],
       [4.21429332e-03],
       [3.08801987e-07],
       [1.82317372e-03],
       [2.95110280e-03],
       [5.27571421e-04],
       [3.54923774e-03],
       [2.39521847e-03],
       [5.47808735e-03],
       [3.66800511e-03],
       [1.79901789e-03],
       [2.16923351e-03],
       [2.13875365e-03],
       [1.28261757e-03],
       [5.06137125e-03],
       [2.01313850e-03],
       [2.36363453e-03],
       [9.99966502e-01],
       [1.26253685e-03],
       [1.32948649e-03],
       [4.36969707e-03],
       [1.00515585e-03],
       [3.87237291e-03],
       [5.14587911e-04],
       [1.58239040e-04],
       [3.23576014e-03],
       [4.23287333e-04],
       [4.61364584e-03],
       [1.43708196e-03],
       [4.37364867e-03],
       [4.30822745e-03],
       [2.42374022e-03],
       [3.28765460e-03],
       [1.09473744e-03],
       [3.84323392e-03],
       [2.20207148e-03],
       [3.98124522e-03],
       [1.97468745e-03],
       [3.01122060e-03],
       [9.52527407e-05],
       [8.08195677e-04],
       [1.51959585e-03],
       [3.65105894e-04],
       [3.28280823e-03],
       [2.07531219e-03],
       [2.84425635e-03],
       [1.34162954e-03],
       [9.06889793e-03],
       [5.51185167e-06],
       [1.58746485e-02],
       [1.33588293e-03],
       [3.05749848e-03],
       [3.22237099e-03],
       [1.78917625e-03],
       [2.67590978e-03],
       [2.92553072e-04],
       [4.45466861e-03],
       [9.73962307e-01],
       [4.47613746e-03],
       [1.98419695e-03],
       [2.26314156e-03],
       [3.42750712e-03],
       [2.11701379e-04],
       [2.05161609e-03],
       [4.93353792e-03],
       [2.33464125e-05],
       [3.47092934e-03],
       [8.35286046e-04],
       [4.40074783e-03],
       [4.51799249e-03],
       [1.80179882e-03],
       [4.94042039e-03],
       [5.03795396e-04],
       [1.64552859e-03],
       [2.82533583e-03],
       [1.57198764e-03],
       [1.63531560e-03],
       [2.83470703e-03],
       [3.67106288e-03],
       [3.60779697e-03],
       [3.25576426e-03],
       [4.28001840e-07],
       [2.29513459e-03],
       [1.13305566e-03],
       [1.90986588e-03],
       [1.39605673e-03],
       [1.17302919e-03],
       [1.91596756e-03],
       [1.46158866e-03],
       [2.61826627e-03],
       [2.09026365e-03],
       [4.42145858e-03],
       [3.42815369e-03],
       [6.62549050e-04],
       [5.99559629e-04],
       [4.45859088e-03],
       [2.37556000e-04],
       [2.37421831e-03],
       [2.53411545e-03],
       [3.56357405e-03],
       [3.74930282e-03],
       [3.90495872e-03],
       [1.89094478e-03],
       [3.02877830e-04],
       [5.16577275e-05],
       [3.24067450e-03],
       [2.49846210e-03],
       [4.46737465e-03],
       [4.08224808e-03],
       [3.18132946e-03],
       [1.81862677e-03],
       [2.01347153e-04],
       [2.94484198e-03],
       [1.87554723e-03],
       [6.88252097e-04],
       [9.96767660e-04],
       [3.40765429e-04],
       [2.06182990e-03],
       [1.00000000e+00],
       [4.27505060e-04],
       [3.44801531e-03],
       [3.34254280e-03],
       [3.82430590e-04],
       [1.39094272e-03],
       [3.16357560e-04],
       [3.41217429e-03],
       [4.16120235e-03],
       [5.68064279e-04],
       [2.71055265e-03],
       [3.28199542e-03],
       [4.57622251e-03],
       [2.82529276e-03],
       [3.99626000e-03],
       [3.64007647e-05],
       [2.18006759e-03],
       [2.16407375e-03],
       [1.59533019e-03],
       [2.90908804e-03],
       [2.24041380e-03],
       [3.47512797e-03],
       [1.19213131e-03],
       [3.09320726e-03],
       [9.81258345e-04],
       [3.45975533e-03],
       [5.69051318e-03],
       [2.83732987e-03],
       [3.38071468e-03],
       [4.42597130e-03],
       [4.39105602e-03],
       [2.37676781e-03],
       [3.69180751e-04],
       [1.29774503e-06],
       [4.86070523e-03],
       [2.85634934e-03],
       [9.26467776e-01],
       [4.48668655e-03],
       [3.72323277e-03],
       [2.51085544e-03],
       [1.36624090e-03],
       [1.55568980e-08],
       [3.32837645e-03],
       [5.70757838e-04],
       [3.80596379e-03],
       [3.99394333e-03],
       [1.67880172e-03],
       [3.93159594e-03],
       [3.94721376e-03],
       [3.20326281e-03],
       [4.00687009e-03],
       [1.82542099e-05],
       [1.77562225e-03],
       [8.90919939e-04],
       [3.14415386e-03],
       [2.42654327e-03],
       [1.85149511e-05],
       [1.86036974e-02],
       [1.05972181e-03],
       [5.07073291e-03],
       [3.29312962e-03],
       [2.91301752e-03],
       [6.74437615e-04],
       [1.27644344e-05],
       [1.52927358e-03],
       [2.81624892e-03],
       [1.16618851e-03],
       [3.27798693e-06],
       [1.67019037e-03],
       [4.46033059e-03],
       [3.00971791e-03],
       [9.75410294e-05],
       [2.59540835e-03],
       [1.65949215e-03],
       [3.05736763e-03],
       [6.47374254e-05],
       [5.00405021e-03],
       [2.24676612e-03],
       [2.25585559e-03],
       [3.80699616e-03],
       [2.05220276e-04],
       [9.83418897e-04],
       [5.20416070e-04],
       [7.04107946e-03],
       [5.01304260e-03],
       [3.85615299e-03],
       [3.86443338e-03],
       [2.54559657e-03],
       [2.95787584e-03],
       [4.19408269e-03],
       [5.41603426e-04],
       [1.05227184e-04],
       [4.76569185e-05],
       [1.96577166e-03],
       [5.23044320e-04],
       [3.58134182e-03],
       [2.51565268e-03],
       [3.41615989e-04],
       [5.61651657e-04],
       [1.65286451e-03],
       [3.30802076e-03],
       [2.94053298e-03],
       [1.22694799e-03],
       [7.38122399e-05],
       [7.99278170e-02],
       [1.79774943e-03],
       [4.37611155e-03],
       [1.19781122e-03],
       [7.74294494e-06],
       [4.07064753e-03],
       [2.24386691e-03],
       [4.32694517e-03],
       [3.23140586e-04],
       [5.28571079e-04],
       [2.07406323e-04],
       [1.61514827e-03],
       [3.05115315e-03],
       [1.64519824e-05],
       [2.11445638e-03],
       [3.50339012e-03],
       [5.31688966e-05],
       [2.73682480e-03],
       [2.06094910e-03],
       [4.65620635e-03],
       [8.80492094e-04],
       [2.90604960e-03],
       [2.73636146e-03],
       [2.62543606e-03],
       [4.26763017e-03],
       [2.52958760e-03],
       [4.06693993e-03],
       [9.98938107e-04],
       [2.71807285e-03],
       [2.05773395e-03],
       [1.49123603e-03],
       [1.83169742e-03],
       [2.06939061e-03],
       [9.85634863e-01],
       [2.31239642e-03],
       [4.72744694e-03],
       [2.88548094e-04],
       [2.63540866e-03],
       [1.30182480e-05],
       [4.12560394e-03],
       [3.19632725e-03],
       [2.21704994e-03],
       [5.03769331e-03],
       [4.03251306e-06],
       [9.99884605e-01],
       [1.10364851e-07],
       [1.53851917e-03],
       [1.49732479e-03],
       [1.83158452e-04],
       [2.59782624e-04]], dtype=float32)

In [22]:
len(y_all)

493

In [23]:
y_all[1][0]

0.00039138086

In [24]:
len(nse_companies)

493

In [25]:
i=0
alert_count = 0
for company in nse_companies:
    #print(i)
    #for prob in y_all:
    if y_all[i][0] >= 0.5:
        
            print(company)
            alert_count = alert_count +1
            i = i+1 
            continue
    i = i+1    

print('Today there is ',alert_count,'stocks triggered')

BCG.NS
CROMPTON.NS
INFY.NS
LTIM.NS
ORIENTELEC.NS
RAJESHEXPO.NS
VIJAYA.NS
ZEEL.NS
Today there is  8 stocks triggered

In [26]:
import tensorflow as tf
print(tf.__version__)

2.10.1

In [27]:


# Check that the GPU is visible to TensorFlow
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1

In [28]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]